### ISSUE TITLE
[mopinion] Add new modules reference and mark old as deprecated

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1580]
https://app.mopinion.com/dashboard/inbox/detail/3312110

`Rocks reference` абсолютно устарела. Нет queue, cartridge, luatest, зато есть shard и tdb.

https://www.tarantool.io/en/doc/latest/reference/

## TODO:
- [ ] Remove `shard` reference from the index
- [ ] Make redirect for `shard` URL to `vshard` reference
- [ ] Add reference for luatest and `cartridge` (just a link)
