### ISSUE TITLE
☂️ Merge documentation branches for 2.x

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1734]
# Problem and Reasoning

At this moment, we have separate documentation branches for Tarantool versions in the 2.x line: 2.0 to 2.6. Branches 2.2–2.6 are published on the website, users can switch between them with a selector. Also published is the `latest` version, a copy of the newest one, currently `2.6`.

This results in some problems and limitations:

* Having lots of versions makes UX worse. Most of the time the version selector is offscreen, so the user has no explicit information about what version they're reading. (Well, except for the version number in the URL).

* It can be useful to read about the changes in the upcoming versions. Say, there's a new feature in the newer version, which can motivate the reader to update their Tarantool. This results in a reduced "earlier versions tail", and fewer reports about bugs which are already fixed.

* User who wants to find differences between two versions has to make a screen-to-screen comparison, or `curl` both documents and then `diff` them. Both options are just insane!

* This versioning doesn't make sense for other projects. The [Cartridge API](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/)/[CLI](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli/) docs have the version selector, but there's just the same content, copied several times. Same for Cartridge k8s-operator and TDG.

* Backporting documentation updates with `git cherry-pick` takes time and doesn't produce much value.

* Building and deploying 6 branches/versions (2, 3, 4, 5, 6, latest) takes 6 times what would be needed for one branch.

* Copy-pasting content on the web can negatively affect SEO and searchability. We've partially fixed SEO with #1452, but Google Search Console still shows us that there are problems (sorry, can't publish them here). 

# Implementation

* One git branch and one version in the selector for each page.
* When a change is effective since some version, we just wrap it in a since-block. Like this:

    > (Some general documentation on bitset index) <br>
    > Since [2.6.2](https://github.com/tarantool/tarantool/releases/tag/2.6.2), [2.7.1](https://github.com/tarantool/tarantool/releases/tag/2.7.1):
    > Bitset index also supports varbinary type.

* We can even publish docs about features in the upcoming versions.

    > Since 2.9.1 (planned)
    > Tarantool now has builds for quantum processor architecture.  
    > This feature is in development, and we appreciate any feedback.

# Subtasks

- [x] find examples of docs mentioning several versions on one page
    * https://www.tarantool.io/en/doc/latest/reference/configuration/#configuration-parameters
    * https://github.com/tarantool/cartridge/blob/master/cartridge/rpc.lua#L68
- [x] write a specification document, pass it to the team for review
- [x] rename 2.6 to `latest` or `master` — #1774  
- [ ] add shortened links to the releases pages (pick either GH releases or the docs)
- [ ] update 2.6 branch with 2.7 content
- [x] add permanent redirects from 2.x to latest

Questionable:

- [ ] add substitution variables like `|current_stable|`, `|current_beta|`, `|previous_stable|` and so on. 

Won't do:
- [x] merge 2.x into `latest`

See also: #1453
