### ISSUE TITLE
[Tech debt] Restructuring Tarantool docs

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2051]
## Description

This is a flat list of tasks related to restructuring docs. The tasks have been collected since 2021.
A [6-stage restructuring plan](https://www.notion.so/tarantool/Tarantool-CE-c075d0db9ce24893beca704c145ae501) has been proposed (internal Notion document).
By October 2022, the two first stages of the plan have been implemented: https://github.com/tarantool/doc/pull/3054, https://github.com/tarantool/doc/pull/3116

## Issues

- [ ] https://github.com/tarantool/doc/issues/2635
- [x] https://github.com/tarantool/doc/issues/2987
- [ ] https://github.com/tarantool/doc/issues/2757
- [ ] https://github.com/tarantool/doc/issues/2663
- [x] https://github.com/tarantool/doc/issues/1996
- [x] https://github.com/tarantool/doc/issues/2667
- [x] https://github.com/tarantool/tarantool.io/issues/1275
- [x] https://github.com/tarantool/doc/issues/2487
- [ ] https://github.com/tarantool/doc/issues/1655
- [ ] https://github.com/tarantool/doc/issues/2731
- [x] https://github.com/tarantool/doc/issues/2734
- [ ] https://github.com/tarantool/doc/issues/2748
- [x] https://github.com/tarantool/doc/issues/3148

### Issues regarding individual topics

- [x] https://github.com/tarantool/doc/issues/2812
- [x] https://github.com/tarantool/doc/issues/2944
- [x] https://github.com/tarantool/doc/issues/2805
- [ ] https://github.com/tarantool/doc/issues/1542 - might require restructuring Indexes
- [ ] https://github.com/tarantool/doc/issues/1651
- [x] https://github.com/tarantool/doc/issues/1344
- [ ] https://github.com/tarantool/doc/issues/1611
- [ ] https://github.com/tarantool/doc/issues/2996
- [ ] https://github.com/tarantool/doc/issues/1986

### NickVolynkin's idea

Понятное оглавление и навигация
Раздел про основы Тарантула: модель данных, основные понятия
Раздел про коннекторы (драйверы)
Раздел про разработку на Lua
Раздел про кластеризацию
Раздел про администрирование

### NeraverinTarantool's idea

https://docs.google.com/document/d/16SQYAXRaL6H6EEnGXozJevXyVRKDk3QLndLfQrLjaho/edit

## Discussion

https://www.notion.so/tarantool/TBD-b7eb3a91fdb545f8b1bea6755e73778d#99a734c36c174eb5ba6e50b2568073c9

**Comment by andreyaksenov** [comment]
Docs are restructured: https://github.com/tarantool/doc/issues/3817. Future tasks:

- The `Developing applications` section is going to be reworked: https://github.com/tarantool/doc/issues/3920.
- The `Administration` section: https://github.com/tarantool/doc/issues/4154
