### ISSUE TITLE
Epic: Continuous localization

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2055]
- [x] Use Crowdin for localization
- [x] Establish a localization workflow: task management, reviews, quality standards, glossary
- [x] Push translation sources to Crowdin automatically
