### ISSUE TITLE
Epic: Continuous localization, stage 2

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#2073]
Continuation of https://github.com/tarantool/doc/issues/2055.

The documentation translation process should be automated. We need to implement a set of tasks at each stage of tech writer's workflow to maintain 100% translation for each repository containing documentation.

- Tech writer creates PR with a documentation update (rst sources).
  - (push-translation on pull_request) GitHub workflow builds _po_ files from _rst_ and sends them to the same name branch in Crowdin
- Pull translations back
  - (pull-translation on workflow_dispatch) When translation of the corresponding changes is ready, tech writer manually triggers GitHub workflow for the translated branch (PR branch)
- Tech writer or someone responsible merges PR
  - (upload-translation on push to master) GitHub workflow upload merged translations from _po_ files into Crowdin master (or main) branch

Issues:

- [x] https://github.com/tarantool/cartridge/issues/1391

TDG:

- [x] https://github.com/tarantool/tdg-doc/issues/95
- [x] https://github.com/tarantool/tdg-doc/issues/104
- [x] https://github.com/tarantool/tdg-doc/issues/151

tarantool/doc submodules:
- [x] cartridge 
- [x] https://github.com/tarantool/metrics/issues/252
- [x] https://github.com/tarantool/cartridge-cli/issues/569
- [x] https://github.com/tarantool/grafana-dashboard/issues/85
- [x] https://github.com/tarantool/luatest/issues/139
- [x] https://github.com/tarantool/tarantool-operator/issues/104
- [x] https://github.com/tarantool/tntcxx/issues/14

Translation workflows
- [x] https://github.com/tarantool/doc/issues/2208
