### ISSUE TITLE
[3pt] box.info.ro_reason

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#2445]
**Product:** Tarantool
**Since:** 2.10.0-beta2
**Audience/target:** Tarantool users
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_info/
**SME:** @ Gerold103

Related to https://github.com/tarantool/doc/issues/2444
Has a follow-up in https://github.com/tarantool/doc/issues/2953

## Details

The new `box.info` field - `ro_reason` - is `nil` on a writable
instance. On a read-only instance `box.info.ro == true` it reports
an error reason. Currently the list is
- `'election'` - `box.cfg.election_mode` is not `'off'` and this
  instance is not a leader. See `box.info.election` for details.
- `'synchro'` - the synchro queue is owned by some other instance.
  For details see `box.info.synchro`.
- `'config'` - `box.cfg.read_only` is true;
- `'orphan'` - the instance is in orphan state.
Requested by @Gerold103 in https://github.com/tarantool/tarantool/commit/48185e8641fe83be16aa2b93d250ab0482f8e5cb

## ToDo

- [x] - Mention the new field in the list on the main page https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_info/

- [x] Create a child page for the `box.info.ro_reason` and put the description of the reasons there

- [ ] Make cross-reference to the description of the `error_object.reason` (see #2444)

- [ ] Don't forget about the follow-up of the topic in #2953
