### ISSUE TITLE
feedback: Configuration reference - reference to info about _cluster space is missing

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#2534]
**Product:** Tarantool
**Root document:** https://www.tarantool.io/en/doc/latest/reference/configuration/#cfg-replication-replication-anon
**SME:** @ 

## Details

> <…>l can write to temporary and
> replica-local spaces), and it **isn’t| present in the _cluster table|.**

https://www.tarantool.io/en/doc/latest/reference/configuration/#cfg-replication-replication-anon

Что за таблица "_cluster" ? Нужна ссылка на описание этой сущности.

ToDo:
Check out if the info about the `_cluster` space is enough here and make a link to it in the config. reference:
https://www.tarantool.io/en/doc/latest/book/replication/repl_add_instances/#server-startup-with-replication

If the info is not enough, update the article re: replication.

Also, we should use the term `space` instead of `table`.

### To-Do

- [x] change the term `table` to `space` and check this across the docs
- [x] add link to the `box.space._cluster`page  - https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/_cluster/
- [x] compare the description of `replication_anon`in [box.cfg reference](https://www.tarantool.io/en/doc/latest/reference/configuration/#confval-replication_anon) (latest+2.11) and [config reference](https://www.tarantool.io/en/doc/latest/reference/configuration/configuration_reference/#configuration-reference-replication-anon) and update it if necessary
