### ISSUE TITLE
[Epic] Document TT CLI - Part 1

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2553]
Dev board ref.: 
https://github.com/tarantool/roadmap-internal/issues/59
https://github.com/tarantool/tt/issues/8

PM ref.: https://www.notion.so/tarantool/TT-CLI-80cbe807b1d14aaa92a32f936d5271af

Unified command-line interface for Tarantool.

**SME**: @ LeonidVas

Followed-up by #3168 

# Tasks

Create a [Cartridge CLI](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli/)-style reference.

## Batch 1 (10sp)

- [x] #2554
- [x] #2976 
- [x] #2555
- [x] https://github.com/tarantool/doc/issues/2566

## Batch 2 (22sp)

Refer to how Cartridge CLI is written.

- [x] https://github.com/tarantool/doc/issues/3004
- [x] https://github.com/tarantool/doc/issues/2556 
- [x] https://github.com/tarantool/doc/issues/2997
- [x] https://github.com/tarantool/doc/issues/2557
- [x] https://github.com/tarantool/doc/issues/2558
- [x] https://github.com/tarantool/doc/issues/2559
- [x] https://github.com/tarantool/doc/issues/2560
- [x] https://github.com/tarantool/doc/issues/2998

## Batch 3 (8sp) -- completed in Q3 22

- [x] https://github.com/tarantool/doc/issues/3000
- [x] https://github.com/tarantool/doc/issues/3130
-
**Total: 40sp** -- TBD

Other tt doc tasks are moved to https://github.com/tarantool/doc/issues/3168

# Details

https://github.com/tarantool/tt - installation instructions and available commands in the `tt` readme.

We might also need man pages for `tt` commands.
