### ISSUE TITLE
[Epic] Proofread connector docs

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2568]
Related dev issues:
https://github.com/tarantool/roadmap-internal/issues/88
https://github.com/tarantool/roadmap-internal/issues/86
https://github.com/tarantool/roadmap-internal/issues/90

- [x] https://github.com/tarantool/doc/pull/2484
- [x] https://github.com/tarantool/doc/pull/2482
- [x] https://github.com/tarantool/doc/issues/2545
- [x] https://github.com/tarantool/doc/issues/2546

**Note:** PHP, Node.js, and Java are not included in this estimate, although they are listed among the dev tasks.
