### ISSUE TITLE
[Epic] Release notes

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2570]
Start the operational work around March 1.

**Total: 29pt**

Related dev. epic: https://github.com/tarantool/roadmap-internal/issues/69
**SME:** @ Totktonada

Process document to be updated: https://www.notion.so/tarantool/WIP-Release-notes-workflow-b4292dbf8fbd41d58a1983546de4a879

### Writing

- [x] https://github.com/tarantool/doc/issues/2218
- [x] https://github.com/tarantool/doc/issues/1025
- [x] #2571
- [ ] https://github.com/tarantool/tarantool/issues/6430
- [x] https://github.com/tarantool/doc/issues/2544

### Guidelines & process
- [x] https://github.com/tarantool/doc/issues/2111
- [x] https://github.com/tarantool/doc/issues/1285

### Related technical debt

Not an actual part of the epic, but relevant.
See https://github.com/tarantool/doc/issues/2572

**Comment by patiencedaur** [comment]
Only changelog proofreading remains. It is performed each week until the changelog (and the release) is published. Closing the epic because there is nothing more to track here.
