### ISSUE TITLE
[Epic] iproto streams follow-ups

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2589]
**Total: 29pt**

Related dev. epic: https://github.com/tarantool/roadmap-internal/issues/55

This is mostly technical debt. I believe we have to document all the stream-related features in this batch, not only those developed in Q1.22. The [streams page](https://www.tarantool.io/en/doc/latest/book/box/stream/) is relatively small, and there is no mention of streams in the net.box API, although it is directly related to iproto. Many other cross-links are missing, too.

### Keyword "streams"

- [x] https://github.com/tarantool/doc/issues/2503
- [x] https://github.com/tarantool/doc/issues/2308 document conn:new_stream()
- [x] https://github.com/tarantool/doc/issues/2311 document stream begin, commit, and rollback
- [x] https://github.com/tarantool/doc/issues/2402
- [x] https://github.com/tarantool/doc/issues/2419
- [x] https://github.com/tarantool/doc/issues/2418

### box.stat

[Single document to update](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_stat/)

- [x] https://github.com/tarantool/doc/issues/2862
- [x] https://github.com/tarantool/doc/issues/2413
- [x] https://github.com/tarantool/doc/issues/2420
- [x] https://github.com/tarantool/doc/issues/2414
- [x] https://github.com/tarantool/doc/issues/2421

### New Q1 features

- [x] https://github.com/tarantool/doc/issues/2625
