### ISSUE TITLE
[Epic] memtx MVCC followups

### ISSUE THREAD

**Issue by arctic-dreamer** [tarantool/doc#2603]
**Dev board ref**: https://github.com/tarantool/roadmap-internal/issues/54
**PM ref**: https://www.notion.so/tarantool/4cba8210ab174d39ba0e5f631941c78d?v=f40e62bbf4a748f5a6e366e67571ea28&p=4a441fe855e648f596bd973d4ba8c5d7

# Tech debt

- [ ] https://github.com/tarantool/doc/issues/2401

# New

- [ ] https://github.com/tarantool/doc/issues/2602

# Issues that may be relevant

- [ ] https://github.com/tarantool/doc/issues/2503
- [ ] https://github.com/tarantool/doc/issues/2299
- [ ] https://github.com/tarantool/doc/issues/2313
