### ISSUE TITLE
[Tech debt] Contribution: revise guides

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2648]
- Developer contributions
- Translator contributions

# Details

Here are probably all of the associated tickets. We need to revise them, see what's done and what's not. We may need to design the process from scratch---not many things are clear.
- Who maintains the developer style guides?
- What languages do we really need style guides for?
My idea is that we don't repeat what can be found elsewhere on the web.

- [ ] https://github.com/tarantool/doc/issues/1797
- [ ] https://github.com/tarantool/doc/issues/1706
- [ ] https://github.com/tarantool/doc/issues/1717
- [ ] https://github.com/tarantool/doc/issues/1655
- [ ] https://github.com/tarantool/doc/issues/1444
- [ ] https://github.com/tarantool/doc/issues/1473
- [ ] https://github.com/tarantool/doc/issues/1443

Provide any details you consider necessary.
