### ISSUE TITLE
[Tech debt] Replication

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2802]
# Details

- [ ] https://github.com/tarantool/doc/issues/2089
- [ ] https://github.com/tarantool/doc/issues/2088
- [ ] https://github.com/tarantool/doc/issues/1693
- [ ] https://github.com/tarantool/doc/issues/2034
- [ ] https://github.com/tarantool/doc/issues/2044
- [ ] https://github.com/tarantool/doc/issues/2274
- [ ] https://github.com/tarantool/doc/issues/2277
- [ ] https://github.com/tarantool/doc/issues/2590
- [ ] https://github.com/tarantool/doc/issues/2604
- [ ] https://github.com/tarantool/doc/issues/2741
