### ISSUE TITLE
[Tech debt] Errors documentation

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#2960]
# Details

Tarantool errors are listed on the [Database error codes](https://www.tarantool.io/en/doc/latest/reference/reference_lua/errcodes/) page. This documentation hasn't been updated since Tarantool 2.1. We have to actualize it and see what errors are most popular now. See the list of error codes: https://github.com/tarantool/tarantool/blob/master/src/box/errcode.h

- [x] https://github.com/tarantool/doc/issues/1676
- [x] https://github.com/tarantool/doc/issues/2444
- [x] https://github.com/tarantool/doc/issues/2445
- [x] https://github.com/tarantool/doc/issues/2953
- [x] https://github.com/tarantool/doc/issues/3006
- [x] https://github.com/tarantool/doc/issues/3005
- [x] https://github.com/tarantool/doc/issues/2415

**Individual error codes**

- [x] https://github.com/tarantool/doc/issues/2954

Provide any details you consider necessary.
