### ISSUE TITLE
[Tech debt] CRUD & select functions

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#2963]
Issues on behavior change and incorrect/incomplete description of the ``box`` functions like ``select``, ``replace``, and so on.

## Details

- [ ] #2818
- [x] #2838
- [x] #2874
- [ ] https://github.com/tarantool/doc/issues/2530
- [ ] https://github.com/tarantool/doc/issues/2529
- [x] https://github.com/tarantool/doc/issues/2528
