### ISSUE TITLE
[Tech debt] Fiber

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#3063]
# Details

## Errors

- [ ] https://github.com/tarantool/doc/issues/3131

## Doc gaps

- [ ] https://github.com/tarantool/doc/issues/2785
- [ ] https://github.com/tarantool/doc/issues/2007

## Features

2.7.2
- [ ] https://github.com/tarantool/doc/issues/2109

2.8
- [ ] https://github.com/tarantool/doc/issues/2412

2.9.0-43-g9da7e03e8 (2.10?)
- [ ] https://github.com/tarantool/doc/issues/2164

2.10.0
- [ ] https://github.com/tarantool/doc/issues/2830

2.10.1? 2.11?
- [x] https://github.com/tarantool/doc/issues/3057
- [x] https://github.com/tarantool/doc/issues/2989

Multiple versions
- [ ] https://github.com/tarantool/doc/issues/1671
