### ISSUE TITLE
feedback: Начало знакомства

### ISSUE THREAD

**Issue by TarantoolBot** [tarantool/doc#3146]
**Product:** Tarantool
**Root document:** https://www.tarantool.io/en/doc/2.11/getting_started/getting_started_imcp/#setting-up-http-api-2-minutes
**SME:** @ artur-barsegyan 

## Details

> <…>ommand below with the corresponding UUIDs:
> curl -X POST --data **"|video_id=|...&user_id=..."** url/like_video
> 
> 
> Получится примерно вот так:
> 
> 
> <…>

https://www.tarantool.io/ru/doc/2.11/getting_started/getting_started_imcp/

There are no directions on how to actually upload a video. Therefore, it is not possible to like it since there is no video_id.

## ToDo

Actually, the `video_id` is there: we get it from the previous request, namely,
```
curl -X POST --data "description=My first tiktok" url/add_video
```

Perhaps, the description is not clear.

ToDo:

- [ ] Create a subsection specifically for sending requests
- [ ] Update the description to make it more clear what IDs the reader is getting and when 
- [ ] Translate the updated content
