### ISSUE TITLE
[Epic] Restructure docs, stage 3

### ISSUE THREAD

**Issue by patiencedaur** [tarantool/doc#3175]
**Total: 20 sp**

Plan: https://www.notion.so/tarantool/Tarantool-CE-c075d0db9ce24893beca704c145ae501#73937305a57442579723413d85dde0be

# Details

- [x] #3179 
- [x] #3180 
- [ ] #3177
- [ ] https://github.com/tarantool/doc/issues/2635
- [ ] #3178 
- [x] https://github.com/tarantool/doc/issues/2667
- [ ] Put the chapter together as described below
- [ ] Fix all broken links
- [ ] Add redirects ([instruction](https://www.notion.so/tarantool/5b0e1ab45d0841a3b502cfea89829ef7))

## Desired structure of the Developer's Guide

Menu item order is TBD.

- Tarantool Lua syntax
- CRUD operations
- Triggers
- Internals (provide external link to [tarantool.io/en/dev/core](http://tarantool.io/en/dev/core))
- Developing with Cartridge (temporarily link to Cluster on Cartridge)
- Links (one page, below are the contents)
    - Awesome Tarantool
    - Tutorials
    - Best practices
    - Reference

**Comment by andreyaksenov** [comment]
Docs are restructured: https://github.com/tarantool/doc/issues/3817. Future tasks:

- The `Developing applications` section is going to be reworked: https://github.com/tarantool/doc/issues/3920.
- The `Administration` section: https://github.com/tarantool/doc/issues/4154
