### ISSUE TITLE
Documentation CI/CD stability and QoL improvements

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#3239]
Documentation CI/CD stability and quality-of-life improvements.

- [x] https://github.com/tarantool/doc/issues/3234
- [ ] https://github.com/tarantool/doc/issues/3237
- [ ] https://github.com/tarantool/doc/issues/3238
- [ ] Use fail-fast options in documentation build and deployment scripts
- [ ] Report failures in doc projects to a VK Teams chat
- [ ] Update all doc projects to the newest version of tarantool/doc-builder
- [ ] https://github.com/tarantool/doc/issues/2443

Template for subtasks:

```markdown
- [ ] [tarantool/doc@`latest`](https://github.com/tarantool/doc/tree/latest)
- [ ] [tarantool/doc@`tt`](https://github.com/tarantool/doc/tree/tt)
- [ ] https://github.com/tarantool/enterprise_doc/tree/master
- [ ] https://github.com/tarantool/tdg-doc/tree/latest (2.x)
- [ ] https://github.com/tarantool/tdg-doc/tree/master (1.x)
- [ ] https://github.com/tarantool/tarantool-internals/tree/master
```
