### ISSUE TITLE
[Epic] Document TT CLI - future plans

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#3272]
**Total: 4 sp**

--
Dev board ref.: 
https://github.com/tarantool/roadmap-internal/issues/59
https://github.com/tarantool/tt/issues/8

PM ref.: https://www.notion.so/tarantool/TT-CLI-80cbe807b1d14aaa92a32f936d5271af

Unified command-line interface for Tarantool.

**SME**: @ LeonidVas

Follow-up of #3168

This epic is a container for doc tasks for features that aren't developed yet (as of March 2023).
We don't have specific plans on writing these docs, just defining the possible scope.

# Tasks

Create a [Cartridge CLI](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_cli/)-style reference.

# Batch 5 (9sp)

- [ ] https://github.com/tarantool/doc/issues/2563
- [ ] https://github.com/tarantool/doc/issues/3156
- [x] https://github.com/tarantool/doc/issues/3273
- [ ] https://github.com/tarantool/doc/issues/2562

--
**Total: 9 sp**

**Comment by p7nov** [comment]
One more future plan - `tt enable` - add an app to `instances_enabled`
