### ISSUE TITLE
[Epic] 2.11 SQL

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3372]
**Related dev. epic:** 
**PM ref.:**
**SME:** @ ImeevMA 

# Scope of work

- [x] https://github.com/tarantool/doc/issues/2865
- [x] https://github.com/tarantool/doc/issues/2884
- [x] https://github.com/tarantool/doc/issues/3184
- [x] https://github.com/tarantool/doc/issues/3243
- [x] https://github.com/tarantool/doc/issues/3244
- [x] https://github.com/tarantool/doc/issues/3245
- [x] https://github.com/tarantool/doc/issues/3246
- [x] https://github.com/tarantool/doc/issues/3281
