### ISSUE TITLE
[Epic] Read views

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3376]
**Related dev. epic:** https://github.com/tarantool/tarantool-ee/issues/140
**PM ref.:** https://www.notion.so/tarantool/Read-view-for-MemTX-engine-2e94e581f9a74c6d9d02f966e360d767
**SME:** @ locker

## Scope of work

- [x] https://github.com/tarantool/enterprise_doc/issues/194
- [x] https://github.com/tarantool/doc/issues/3337
- [x] https://github.com/tarantool/enterprise_doc/issues/203
