### ISSUE TITLE
[Epic] HTTP client enhancements

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3377]
**SME:** @ ligurio, @ oleg-jukovec

## Scope of work

- [x] https://github.com/tarantool/doc/issues/3142
- [x] https://github.com/tarantool/doc/issues/3143
- [x] https://github.com/tarantool/doc/issues/3153
- [x] https://github.com/tarantool/doc/issues/3152
- [x] https://github.com/tarantool/doc/issues/3280
- [x] https://github.com/tarantool/doc/issues/3344

**What's new**: [HTTP client enhancements](https://www.tarantool.io/en/doc/latest/release/2.11.0/#http-client-enhancements)
**Announcement**: [HTTP client enhancements](https://github.com/orgs/tarantool/discussions/8371#user-content-http-client-enhancements)

Todo:
- Add links to new topics in What's new.
