### ISSUE TITLE
Deprecate tarantoolctl and cartridge-cli in docs

### ISSUE THREAD

**Issue by NeraverinTarantool** [tarantool/doc#3501]
Original request:
"Мы начинаем рекомендовать нашим пользователям использовать tt на замену старым CLI инструментам.

При этом в документации осталось немало гайдов, где показано как сделать те или иные операции с помощью старых cli.

Наша задача актуализировать эти гайды и заменить все на команды tt cli.
Изменения необходимо выполнить в Tarantool 2.11, Tarantool EE 2.11.
Разделы относящиеся к tarantoolctl и cartridge-cli также пометить как deprecated и рекомендовать переходить на tt cli"

## Description

[tt CLI](https://github.com/tarantool/tt/) is released and ready to replace `tarantoolctl` and `cartridge-cli`. We need to adjust command-line instruction across Tarantool docs to use the new tool.

`tt` must be the recommended Tarantool CLI since version 2.11. Thus, we will replace `tarantoolctl` and `cartridge-cli` in Tarantool CE and Tarantool EE **2.11** docs. 

`tarantoolctl` and `cartridge-cli` must be marked as deprecated tools. Additionally, we should provide instructions on migration from them to `tt`. They are available in the [tt repo](https://github.com/tarantool/tt/blob/master/doc/examples.md#transition-from-tarantoolctl-to-tt)

The scope of work is defined in [Notion](https://www.notion.so/tarantool/Tarantool-3-0-78ac037bcfbd4b068d0b409c06b3749e). It includes:
- CE docs:
  - 30-40 examples of tarantoolctl usage that require writing a tt alternative.
  - 80 occurrences of the word `tarantoolctl` that can be trivially replaced with ``tt``.
  - 20 other occurrences
- EE docs:
  -  11 occurrences of the word `tarantoolctl` that can be trivially replaced with ``tt``.

## Pages affected the most

- **Administration** section
  - https://www.tarantool.io/en/doc/latest/book/admin/start_stop_instance/
  - https://www.tarantool.io/en/doc/latest/book/admin/daemon_supervision/
  - https://www.tarantool.io/en/doc/latest/book/admin/instance_config/
  - https://www.tarantool.io/en/doc/latest/book/admin/logs/
  - https://www.tarantool.io/en/doc/latest/book/admin/server_introspection/
  - https://www.tarantool.io/en/doc/latest/book/admin/troubleshoot/
- How-to
  - https://www.tarantool.io/en/doc/latest/how-to/vshard_quick/
- EE docs: 
  - https://www.tarantool.io/en/enterprise_doc/dev/

## Question

Q: Do we need to replace `cartridge-cli` calls in **Cartridge docs** with `tt`?

A: No, a deprecation note with a link to tt docs is enough for Cartridge docs.

## Definition of done

- [x] All command-line calls in Tarantool CE and EE docs use tt
- [x] tarantoolctl reference page contains a deprecation note and a link to tt as a replacement
- [x] cartridge docs contain a deprecation note for cartridge-cli (but still use it in cartridge-specific examples)
- [x] Tarantool CE docs provide guidelines for migration from tarantoolctl and cartridge-cli to tt

**Comment by p7nov** [comment]
Фронт работ:
В tarantool/doc:
- 🛠️ **~30-40** вхождений: требуется написание и тестирование аналогичных вызовов tt.
- 🍹 **~80** вхождений: тривиальна замена – упоминание названия в тексте.
- ❓**~20** погрешность - относятся к одной из категорий выше.

В tarantool/enterprise-doc: 11 вхождений tarantoolctl, все тривиальны.

Дополнительно: в репо tarantool/tt есть [инструкции по миграции со старых утилит](https://github.com/tarantool/tt/blob/master/doc/examples.md). Добавим их в соответствующие разделы доки.

[Подробнее в Notion](https://www.notion.so/tarantool/Tarantool-3-0-78ac037bcfbd4b068d0b409c06b3749e).

**Comment by p7nov** [comment]
Pull requests:
- Tarantool CE docs (main) https://github.com/tarantool/doc/pull/3706
- Tarantool EE docs: https://github.com/tarantool/enterprise_doc/pull/247
- Cartridge docs: https://github.com/tarantool/cartridge/pull/2145
- Cartridge CLI docs: https://github.com/tarantool/cartridge-cli/pull/780
