### ISSUE TITLE
[Epic] 3.x Migration guide

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#3516]
**Product:** Tarantool
**Since:** 2.11
**Audience/target:** all
**Root document:** TBD
**SME:** @ TBD

# Details

Provide a guide with instructions on migrating to 3.0 from supported earlier versions.

Scope:
- [ ] Tarantool 2.x upgrade to 3.x (is it equal installing 3.0?)
- [ ] Configuration migration 2.11 > 3.0
- [x] migration from tarantoolctl and Cartridge CLI to tt cli - **content is ready**, TDB - move to the Migration guide
- [ ] **?** Cartridge application migration to 3.0 **if possible**
- [ ] **?** TCM-related migration 
- [x] <s>Connectors: migration of Python/Java/\<any language]> code that works with Tarantool 2.x</s> - IPROTO is fully compatible, no migration is required.

# Tasks

- [ ] #3661

**Comment by andreyaksenov** [comment]
See also: https://github.com/tarantool/tt/issues/924

**Comment by p7nov** [comment]
[RFC: Upgrade from 2.x to 3.x](https://confluence.vk.team/pages/viewpage.action?pageId=1244279661)
