### ISSUE TITLE
Make vinyl experimental

### ISSUE THREAD

**Issue by NeraverinTarantool** [tarantool/doc#3523]
Движок vinyl получил статус Экспериментального.

В связи с этим в документации необходимо:

- [ ] Добавить в документацию отдельную страницу со списком экспериментальных технологий и пояснения, что именно значит этот статус
- [ ] Занести vinyl в список экспериментальных технологий
- [ ] Везде в документации, где сейчас встречается vinyl, сделать отметку о том, что это экспериментальная технология и дать ссылку на страницу про экспериментальные технологии
- [ ] Сделать перевод на русский этого нового контента, в первую очередь страницы про экспериментальные технологии

Экспериментальные технологии:
- не рекомендуется использовать на production
- документация на экспериментальные технологии не развивается и может не отражать реальную работу экспериментальной технологии
- поддержка экспериментальных технологий не оказывается
- команда не берет на себя никаких обязательство по исправлению ошибок, в том числе критических, в экспериментальных технологиях
- модули, а также инструменты, могут не поддерживать работу с экспериментальными технологиями

**Comment by veod32** [comment]
> страницу со списком экспериментальных технологий

Сейчас в Тарантуле (СЕ, ЕЕ) есть ли еще что-то, что мы позиционируем как эспериментальную технологию? 
Чтобы это тоже было в списке.

**Comment by NeraverinTarantool** [comment]
@veod32 пока нет, но есть пара кандидатов, по которым ведется обсуждение

**Comment by andreyaksenov** [comment]
Приблизительный план:
- Создать новый топик `Stability of Tarantool components`. Есть хороший пример в документации Kotlin: [Stability of Kotlin components](https://kotlinlang.org/docs/components-stability.html). Можно положить его в секцию [Releases](https://www.tarantool.io/en/doc/latest/release/).
- Помимо `Experimental` уровня, нужно добавить другие уровни стабильности, описания которых можно взять из секции [Pre-release versions](https://www.tarantool.io/en/doc/latest/release/policy/#pre-release-versions). Из этой секции можно дать ссылку на новый `Stability` топик.
- Добавить красную ноту вверху следующих топиков о том что **vinyl** экспериментальный, со ссылкой на топик `Stability`:
   * https://www.tarantool.io/en/doc/latest/concepts/engines/vinyl/ 
   * https://www.tarantool.io/en/doc/latest/concepts/engines/
   * https://www.tarantool.io/ru/doc/latest/concepts/engines/memtx_vinyl_diff/
 - Везде, где встречается слово _vinyl_ (включая АПИ мемберы), дать ссылку на страницу https://www.tarantool.io/en/doc/latest/concepts/engines/vinyl/. Добавить ссылки из документации Tarantool Enterprise.
 - Чтобы увеличить visibility того что vinyl экспериментальный, можно подумать про добавление тултипов на hover соответствующих линков: https://sphinx-hoverxref.readthedocs.io/en/latest/index.html. Но это требует отдельного экстеншена в доке.
 

Помимо vinyl, нашел упоминание **experimental** для следующих компонентов:
- Apple M1 beta - Experimental support for Apple M1 Macs - тут смущает что есть и beta, и experimental
- https://github.com/FZambia/tarantool - экспериментальный Go клиент
- [Hot-reload](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.roles/#reload) в картридже
- Experimental GC64 mode for LuaJIT - этот режим все еще экспериментальный?
- [tt daemon](https://github.com/tarantool/tt#working-with-tt-daemon-experimental)

Нужно понять что из этого стоит добавить в лист экспериментальных компонентов.

**Comment by NeraverinTarantool** [comment]
- Apple M1 beta, с ним все лучше, чем с vinyl, плюс мы работаем над всеми известными проблемами
- https://github.com/FZambia/tarantool  - можно вообще удалить из документации, чтобы не путать пользователей
- Hot-reload в картридже нет смысла как-то помечать, он вполне работает, просто включать надо отдельно
- GC64 - уже не experimental
- tt daemon, да можно пока пометить как experimental

**Comment by p7nov** [comment]
From #3578 
> Let's change that to "vinyl is a completely different experimental storage engine featuring an LSM-tree implementation. Not 100% compatible with the memtx engine"
