### ISSUE TITLE
[Epic] 3.0 config - Part 1

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3544]
**Next doc epic:** https://github.com/tarantool/doc/issues/3957

**PM ref.:** [Notion link](https://www.notion.so/tarantool/Getting-Started-with-3-0-03d461efc01c43dd9e09f2bc4903717b)
**SME:** @ Totktonada , @ igormunkin, @ Mons   

## Doc issues

**Estimation:** ~ 44 sp is done (8.12.2023).
**Estimation:** ~ 54 / 154 sp is done (20.12.2023).

### Getting Started

- [x] https://github.com/tarantool/doc/issues/3704

### Concepts

- [x] https://github.com/tarantool/doc/issues/3651
- [x] https://github.com/tarantool/doc/issues/3652
- [x] https://github.com/tarantool/doc/issues/3658

### How-to

- [x] https://github.com/tarantool/doc/issues/3653
- [x] https://github.com/tarantool/doc/issues/3654
- [x] https://github.com/tarantool/doc/issues/3655
- [x] https://github.com/tarantool/doc/issues/3656

### Administration

- [x] https://github.com/tarantool/doc/issues/3879
- [x] https://github.com/tarantool/doc/issues/3673
- [x] https://github.com/tarantool/doc/issues/3791

### Reference

- [x] https://github.com/tarantool/doc/issues/3663
- [x] https://github.com/tarantool/doc/issues/3851

### Misc

- [x] [SQL] https://github.com/tarantool/doc/issues/3672

**Comment by andreyaksenov** [comment]
Here is a rough overview on what should be done regarding new configuration approach.

# New topics and structure

This section shows a draft version of TOC structure that takes into account new topics:

- Concepts
    - Configuration
        - Config file (see the concepts above)
        - Environment variables (content from [Setting via environment variables](https://www.tarantool.io/en/doc/latest/reference/configuration/#setting-via-environment-variables), `tarantool --help-env-list`)
        - Lua code (old approach, take content from [Initialization file](https://www.tarantool.io/en/doc/latest/reference/configuration/#initialization-file), see the **Notes** below)
- How-tos (see also [Getting Started with 3.0](https://www.notion.so/tarantool/Getting-Started-with-3-0-03d461efc01c43dd9e09f2bc4903717b) and existing replication tutorials)
    - Single instance
    - Replicaset
    - Master-master (manual managing ro/rw)
    - Failover using Raft (failover: election)
    - Etcd
- ...
- Administration
    - Upgrades
        - Upgrade from 2.11 to 3.0
- Reference
    - Yaml reference (including Environment Variables reference)
    - box.cfg reference
    - [Submodule box.cfg](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_cfg/)
    - ...
    - config module API
- Releases
    - 3.0
        - Migrating configuration from 2.11 to 3.0


> **Notes**
> - The new approach uses new environment variable names in many cases. Support of old names not implemented yet. (see also https://docs.google.com/spreadsheets/d/1_yEK9N_hBVWIga9mOk7zZzA6Zd3mAq7e5KZsnrbgj30/edit?usp=sharing)
> - Using box.cfg is considered as the internal feature or can be used for quick instance troubleshooting.
> - tt uses `TT_*_DEFAULT` environment variables to avoid conflicts with the file config.

# Existing topics

This section lists topics affected by new configuration approach:

- https://www.tarantool.io/en/doc/latest/how-to/getting_started_db/
The basic tutorial can use the interactive session for simplicity but the configuration file should be mentioned as the production approach. I think, it's worth moving this tutorial to a new Getting Started section (to be created https://github.com/tarantool/doc/issues/3636). In the new Getting Started section, the interactive console might be the first way to try Tarantool. Then, we can show how to run a single instance using a config file, create a replica set, cluster, application, etc.

How-tos that don't demonstrate replication or cluster configuration can use the interactive mode or can be converted to Lua snippets. The configuration approach doesn't affect the feature itself:
- https://www.tarantool.io/en/doc/latest/how-to/db/crud/
- https://www.tarantool.io/en/doc/latest/how-to/db/indexes/
- https://www.tarantool.io/en/doc/latest/how-to/db/sequences/
- https://www.tarantool.io/en/doc/latest/how-to/getting_started_net_box/

Tutorials that show replication or sharding should use the new config. Examples:
- https://www.tarantool.io/en/doc/latest/how-to/vshard_quick/ (see the [example](https://gist.github.com/Totktonada/6339517a32cd7df4ac7df700fc3fa6b8))
- https://www.tarantool.io/en/doc/latest/how-to/replication/ (all tutorials)
See also: https://www.notion.so/tarantool/Getting-Started-with-3-0-03d461efc01c43dd9e09f2bc4903717b

The `Administration` section is also affected:
- https://www.tarantool.io/en/doc/latest/book/admin/


Running Tarantool depends on the configuration approach:
- https://www.tarantool.io/en/doc/latest/how-to/app/launching_app/

Bootstrapping a database for connector tutorials uses the old approach:
- https://www.tarantool.io/en/doc/latest/book/connectors/#setting-up-the-server-for-connector-examples
- https://www.tarantool.io/en/doc/latest/how-to/getting_started_python/#pre-requisites
- https://www.tarantool.io/en/doc/latest/how-to/getting_started_php/
- https://www.tarantool.io/en/doc/latest/how-to/getting_started_go/
- https://www.tarantool.io/en/doc/latest/how-to/getting_started_cxx/#starting-tarantool-and-creating-a-database

Affected SQL topics:
- https://www.tarantool.io/en/doc/latest/how-to/sql/sql_tutorial/#initialize
- https://www.tarantool.io/en/doc/latest/how-to/sql/improving_mysql/

Vshard configuration reference:
- https://www.tarantool.io/en/doc/latest/reference/reference_rock/vshard/vshard_ref/

Tarantool EE:
- https://www.tarantool.io/en/enterprise_doc/setup/#network-requirements
- https://www.tarantool.io/en/enterprise_doc/security/
- https://www.tarantool.io/en/enterprise_doc/audit/
- https://www.tarantool.io/en/enterprise_doc/wal_extensions/
- https://www.tarantool.io/en/enterprise_doc/flight_recorder/
- https://www.tarantool.io/en/enterprise_doc/appendix/audit_log/

Metrics:
- https://www.tarantool.io/en/doc/latest/book/monitoring/api_reference/#lua-function.metrics.cfg

Also: 
- Find all snippets that use `box.cfg { }` and decide whether they should use a new config.
- Check and update all `box.cfg` references (for example, ``:ref:`box.cfg.read_only <cfg_basic-read_only>``).

Migration:
- Basic scenarios: https://docs.google.com/document/d/1bH22TuMDuJEp50vwsgGUCBxt3jt22ve6cKgAKDuAumA/edit?usp=sharing
- Environment variables and options: https://docs.google.com/spreadsheets/d/1_yEK9N_hBVWIga9mOk7zZzA6Zd3mAq7e5KZsnrbgj30/edit?usp=sharing

**Comment by andreyaksenov** [comment]
- [ ] [Getting started] Creating your first Tarantool database
- [ ] [Concepts] Configuration (YAML)
- [ ] [Concepts] Configuration (in code)
- [ ] [How-to] Single instance
- [ ] [How-to] Replicaset
- [ ] [How-to] Master-master (manual managing ro/rw)
- [ ] [How-to] Failover using Raft (failover: election)
- [ ] [How-to] Etcd
- [ ] [Epic] Administration
    - [ ] [Administration] Instance configuration
    - [ ] [Administration] Access control
    - [ ] [Administration] Sharding with vshard
    - [ ] [Administration] Upgrading from 2.11 to 3.0
    - [ ] ...
- [ ] [Reference] Configuration reference (YAML)
- [ ] [Reference] Configuration reference (in code)
- [ ] [Reference] Config module API
- [ ] [Releases] Migrating configuration from 2.11 to 3.0
- [ ] [Epic] Tarantool EE configuration
    - [ ] [EE] Security
    - [ ] [EE] Audit
    - [ ] [EE] WAL extensions
    - [ ] [EE] Flight recorder
- [ ] [How-to] Launching an application
- [ ] [Connectors] Bootstrapping a database in tutorials for connectors
- [ ] [SQL] Bootstrapping a database in tutorials for SQL
- [ ] [Metrics] Metrics configuration

**Comment by andreyaksenov** [comment]
## Details

- [ ] Describe the concept.
  - [x] The idea of a declarative configuration (https://github.com/tarantool/tarantool/issues/8724).
  - [x] The idea of a centralized configuration available in Tarantool EE (https://github.com/tarantool/tarantool-ee/issues/476).
  - [x] Instance and cluster config. Global, group, replicaset, instance scopes in the cluster config. How the cluster config folded into the instance config.
  - [x] Configuration sources: env (CE/EE), file (CE/EE), etcd (EE), env default (CE/EE). Difference between instance/cluster config sources. Sources priority. How the values are merged.
  - [ ] Etcd source: content of the etcd keys (yaml), how the keys are searched, priority of the keys, how the keys are merged.
  - [ ] Etcd source: `config.reload` option and when the configuration is reloaded.
  - [x] CLI options: `--name` (`-n`), `--config` (`-c`), `--help-env-list`.
  - [ ] Instance config schema (https://github.com/tarantool/tarantool/blob/master/src/box/lua/config/instance_config.lua).
  - [ ] Instance config defaults.
  - [x] Templating (`{{ instance_name }}`).
  - [ ] Option constraints: sections/options that can't appear in any scope.
  - [x] Recipe: how to work with etcd.
  - [x] Recipe: how to start an instance without a local file config in EE (configure etcd source from env variables).
  - [x] `replication.peers` option and its default (URI list autoconstruction).
  - [ ] `replication.failover` option and a two phase startup process with configuration reloading.
  - [ ] Configuration examples (https://github.com/tarantool/tarantool/tree/master/doc/examples/config).
  - [ ] Configuration applying idempotence: how the config's 'target state' approach differs from the 'state changes' `box.cfg()` approach.
  - [ ] How non-dynamic box.cfg() options are applied (no error, wait for restart).
  - [ ] `config` module API: `:get()`, `:info()`, `:reload()`.
  - [ ] How and when status is changed (state diagram).
- [ ] Step-by-step/how-to guides
  - [ ] There is a short [Getting Started with 3.0](https://www.notion.so/tarantool/Getting-Started-with-3-0-03d461efc01c43dd9e09f2bc4903717b) document from @Mons.

## Demo:

Recording: https://cloud.mail.ru/public/3KEi/gnVzVELJL
Notes: https://www.notion.so/tarantool/Getting-Started-with-3-0-03d461efc01c43dd9e09f2bc4903717b

## Demo 2024-08-24 (3.0.0-alpha2)

Recording: https://cloud.mail.ru/public/ANBh/WPUNQk8Wg
Slides: https://docs.google.com/presentation/d/1nGGOLzVik4vGppN9jpbLXsXCMl-M4j9--ZC_nEkyHb0/edit?usp=sharing
Sharding example code: https://gist.github.com/Totktonada/6339517a32cd7df4ac7df700fc3fa6b8

## State diagram

```mermaid
stateDiagram-v2
    pre_ready: ready
    pre_check_warnings: check_warnings
    pre_check_errors: check_errors
    wait_for_reload: wait for config#colon;reload()
    note left of pre_check_errors: waits for config#colon;reload()

    [*] --> startup_in_progress: broadcast
    startup_in_progress --> _collect

    wait_for_reload --> reload_in_progress: broadcast
    reload_in_progress --> _collect

    _collect --> _apply

    state _apply {
        [*] --> pre_ready: broadcast
        [*] --> pre_check_warnings: broadcast
        [*] --> pre_check_errors: broadcast
    }

    pre_ready --> _post_apply
    pre_check_warnings --> _post_apply
    _apply --> wait_for_reload

    state _post_apply {
        [*] --> ready: broadcast
        [*] --> check_warnings: broadcast
        [*] --> check_errors: broadcast
    }

    _post_apply --> wait_for_reload
```
