### ISSUE TITLE
[Epic] Cartridge deprecation in 3.0

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3546]
**PM ref.:** [Notion 1](https://www.notion.so/tarantool/Tarantool-Clusters-Manager-7a8d7757d9d7487fa591d47e4c3edc51), [Notion 2](https://www.notion.so/tarantool/WIP-New-Cartridge-d99c0aedc60841bdbaf32042081da15a#957f57b2da114bada9627cbb72aa7ee0)
**SME:** @ filonenko-mikhail

## Details

**Get started**

Remove the section and all nested pages: 
- [x] https://www.tarantool.io/en/doc/latest/getting_started/

> Write new Getting Started in https://github.com/tarantool/doc/issues/3636
   
**Concepts/how-to**

Remove the sections below, add redirects to TCM:
- [x] https://www.tarantool.io/en/doc/latest/book/cartridge/:
  - [x] Remove ToC item
  - [x] Remove git submodules `cartridge` and `cartridge-cli`
  - [x] Remove cartridge from build steps in the repo
  - [x] Remove cartridge from GitHub build workflow
- [x] https://www.tarantool.io/en/doc/latest/how-to/getting_started_cartridge/
- [x] https://www.tarantool.io/doc/latest/book/cartridge
- [ ] https://www.tarantool.io/en/doc/latest/book/admin/upgrades/upgrade_cluster/ (Create a TCM version)

**Misc**
- [x] https://www.tarantool.io/en/doc/latest/concepts/data_model/migrations/#how-you-can-apply-migration
- [x] https://www.tarantool.io/en/doc/latest/concepts/data_model/schema_desc/#data-schema-description-using-the-ddl-module
- [x] https://www.tarantool.io/en/doc/latest/concepts/#application-server
- [x] https://www.tarantool.io/en/doc/latest/concepts/modules/
- [x] https://www.tarantool.io/en/doc/latest/contributing/contributing/#documentation-how-to-report-and-fix-problems
- [ ] https://www.tarantool.io/en/doc/latest/book/connectors/java/
- [x] https://www.tarantool.io/en/doc/latest/contributing/docs/localization/locstate/
- [x] https://www.tarantool.io/en/doc/latest/contributing/docs/localization/glossaries/#cartridge
  - [x] Merge glossaries `Tarantool core` and `Cartridge`
  - [x] Remove `Cartridge` glossary

**TT CLI**

Add notes that Cartridge is deprecated:
- [x] https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/ (not potential - actual)
- [x] https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/build/#pre-build-and-post-build-scripts
- [x] https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/create/#examples
- [x] https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/init/#details

**Tarantool EE**
- [x] https://www.tarantool.io/en/enterprise_doc/migration/
- [x] https://www.tarantool.io/en/enterprise_doc/rocksref/
- [x] https://www.tarantool.io/en/enterprise_doc/admin/
- [x] https://www.tarantool.io/en/enterprise_doc/audit/
- [x] https://www.tarantool.io/en/enterprise_doc/cartridge-auth/
- [x] https://www.tarantool.io/en/enterprise_doc/dev/
- [x] https://www.tarantool.io/en/enterprise_doc/setup/#package-contents
- [ ] https://www.tarantool.io/en/enterprise_doc/modules/space-explorer/rst/topics/README.md/ ???

**Migration question**
Should we create a migration guide somewhere? For example, in TCM docs (but in this case it should be kept actual) or in a blog.

As discussed with @ kyukhin no way to automate the apps migration from Cartridge to Tarantool EE 3.0+ is planned. It it likely that developers will have to write their apps from scratch.

**Other action points to remember**
- replace `Cartridge` in the `Documentation` chooser with `TCM` - to decide in scope of restructurization. TCM doc is currently suggested to be a top-level section, not a separate guide.
- `try.tarantool.io` uses Cartridge now
- Cartridge site page: https://www.tarantool.io/en/cartridge/
- readme: https://github.com/tarantool/cartridge
- readme: https://github.com/tarantool/cartridge-java

**Comment by p7nov** [comment]
In result of #3780, we should add redirects for removed pages. They should be set up when publishing Tarantool 3.0 docs together with other redirects we'll need in scope of doc restructurization.

Below is the list of Cartridge-related redirects:

- https://www.tarantool.io/en/doc/latest/book/cartridge/* (all pages) > https://www.tarantool.io/en/doc/2.11/book/cartridge/*
- https://www.tarantool.io/en/doc/latest/getting_started/* (all pages) > https://www.tarantool.io/en/doc/latest/getting_started/
- https://www.tarantool.io/en/doc/latest/how-to/getting_started_cartridge/ > https://www.tarantool.io/en/doc/2.11/how-to/getting_started_cartridge/
- https://www.tarantool.io/en/doc/latest/enterprise/migration/ > https://www.tarantool.io/en/doc/latest/enterprise/
- https://www.tarantool.io/en/doc/latest/enterprise/dev/ > https://www.tarantool.io/en/doc/latest/enterprise/
- https://www.tarantool.io/en/doc/latest/enterprise/cartridge-auth/ > https://www.tarantool.io/en/doc/latest/enterprise/
- https://www.tarantool.io/en/doc/latest/enterprise/admin/ > https://www.tarantool.io/en/doc/latest/reference/tooling/tcm/
