### ISSUE TITLE
[Epic] Merging CE and EE documentation

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3547]
**SME:** @ expert to ask for more information

### Doc tasks

- [x] Move content from EE docs to https://github.com/tarantool/doc: create a new `Tarantool Enterprise` node and move all content there without additional restructuring.
- [x] Update external links to EE topics to internal ones (see the affected CE topics below).
- [x] Update EE links that lead to CE topics (these links look like `<community:`).
- [ ] [Set up](https://www.tarantool.io/en/doc/latest/contributing/docs/infra/) docs for external submodules (https://github.com/tarantool/enterprise_doc/issues/245).
- [x] Rework the `Appendixes` section, for example:
    - Remove https://www.tarantool.io/en/enterprise_doc/appendix/parameters/
    - Move https://www.tarantool.io/en/enterprise_doc/appendix/audit_log/ to https://www.tarantool.io/en/doc/latest/reference/reference_lua/ and add the admonition (like in [tt export](https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/export/)).
    - https://www.tarantool.io/en/enterprise_doc/appendix/system_metrics/ move to the top level
    - https://www.tarantool.io/en/enterprise_doc/appendix/deprecated/ move to the top level
    - https://www.tarantool.io/en/enterprise_doc/appendix/orchestrator_api/ move under the `deprecated` node
- [ ] Update [pdf_toc.rst](https://github.com/tarantool/doc/blob/latest/doc/pdf_toc.rst) used to build PDF (https://github.com/tarantool/doc/pull/3774).

### DevX tasks (tarantool.io)

- [x] Add redirects for moved pages.
- [x] Update site links to EE docs.
- [x] Disable indexing of https://www.tarantool.io/en/enterprise_doc/.

#### DevX tasks (tarantool.io) - Optional

The next items are optional at this point and can be made after introducing a new docs structure (follow-up issue https://github.com/tarantool/doc/issues/3775):

- [ ] Remove the `Tarantool Enterprise` item from the documentation chooser in the docs portal (https://www.tarantool.io/en/doc/latest/).
- [ ] Remove the `Enterprise Edition` item from the `Documentation` chooser in the header (https://www.tarantool.io/), rename `Community Edition` to something else. For example, we can keep two items - `Tarantool` and `Data Grid` (the same for the `Enterprise Edition` doc item in the footer).
- [ ] Remove the `Tarantool Enterprise` item from the footer (https://www.tarantool.io/).
- [ ] Update the EE docs link in the [Customer zone](https://www.tarantool.io/en/accounts/customer_zone/) page to the CE docs link. Can be renamed `Enterprise documentation` -> `Tarantool documentation`.

### Publish merged docs
- [x] Publish merged CE/EE docs. `DevX tasks` above should be finished right after this step.
- [x] Check that all redirects and new links work fine.

### Other tech tasks
- [ ] Stop publication of EE docs to https://www.tarantool.io/en/enterprise_doc/ (DevX). Question: Remove old EE docs completely?
- [ ] Question: Should `TarantoolBot` be updated for creating new EE issues in https://github.com/tarantool/doc? If we want to keep such issues private, the private repository is still [required](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-an-issues-only-repository). So, we can choose one of the following:
    - Keep the https://github.com/tarantool/enterprise_doc repo for EE doc issues.
    - Configure creating EE doc issues in the `tarantool-ee` repo.
- [ ] (Questionable) [Transfer](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) EE doc issues to https://github.com/tarantool/doc.
- [ ] (Questionable) Archive the https://github.com/tarantool/enterprise_doc repo. In the readme file, add a note with a link to https://github.com/tarantool/doc.
