### ISSUE TITLE
[Epic] Documentation localization

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3716]
Finalize localization in Russian for the all content currently untranslated. 

## ToDo

- [ ] CAT implementation (DevX) -- add link to the dev issue
- [ ] Create the list of the untranslated and partially translated pages
- [ ] Cteate the list of pages for which translation exists in .po files but there're technical issues wiht mapping .rst/.pot files to .po
- [ ] Hire external translators
- [ ] Onboard external translators
- [ ] Find and revive the dictionary for translators
