### ISSUE TITLE
[Epic] 3.0 release documentation

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#3719]
Create and publish 3.0 release documentation.

## Scope

- [x] https://github.com/tarantool/doc/issues/3517
- [x] https://github.com/tarantool/doc/issues/3913
- [x] remove an empty guide: [Migrating to declarative configuration](https://docs.d.tarantool.io/en/doc/3.0/concepts/configuration/configuration_migrating/)
- [x] Cleanup empty pages in EE doc section (dev guide, cluster admin guide)

## Website and CI tasks

- [x] tarantool/doc#3955
- [x] tarantool/tarantool.io#1488
