### ISSUE TITLE
[Epic] Replace 'tarantoolctl' usages with 'tt' in readmes for external modules

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#3730]
Original doc issue: https://github.com/tarantool/doc/issues/3501

Affected readmes:

- [ ] https://github.com/tarantool/crud#quickstart - https://github.com/tarantool/crud/pull/374
- [ ] https://github.com/tarantool/http#installation - https://github.com/tarantool/http/pull/194
- [ ] https://github.com/tarantool/mysql#tarantoolctl-rocks - https://github.com/tarantool/mysql/pull/74
- [ ] https://github.com/tarantool/ddl#building-and-testing - https://github.com/tarantool/ddl/pull/116
- [ ] https://github.com/tarantool/metrics#installation - https://github.com/tarantool/metrics/pull/473
- [ ] https://github.com/tarantool/luatest#installation - https://github.com/tarantool/luatest/pull/328
- [ ] https://github.com/tarantool/kafka#installation - https://github.com/tarantool/kafka/pull/105
- [ ] https://github.com/tarantool/expirationd#installation - https://github.com/tarantool/expirationd/pull/158
- [ ] https://github.com/tarantool/vshard#install - https://github.com/tarantool/vshard/issues/438
- [ ] https://github.com/tarantool/tarantool-python#run-tests - https://github.com/tarantool/tarantool-python/issues/313
- [ ] https://github.com/tarantool-php/queue#before-start -https://github.com/tarantool-php/queue/issues/23
- [ ] https://github.com/tarantool/cron-parser#installation - https://github.com/tarantool/cron-parser/pull/11
- [ ] https://github.com/tarantool/tracing#description - https://github.com/tarantool/tracing/pull/19
- [ ] https://github.com/tarantool/frontend-core#rock - https://github.com/tarantool/frontend-core/issues/194
- [ ] https://github.com/tarantool/docker#connect-to-a-running-tarantool-instance - https://github.com/tarantool/docker/pull/265
