### ISSUE TITLE
[Epic] 3.0 config - Part 2

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#3957]
**Previous doc epic:** https://github.com/tarantool/doc/issues/3544
**Next doc epic:** https://github.com/tarantool/doc/issues/4085

**PM ref.:** [Notion link](https://www.notion.so/tarantool/Getting-Started-with-3-0-03d461efc01c43dd9e09f2bc4903717b)
**SME:** @ Totktonada , @ igormunkin

Priority:

1) General config settings (memtx, persistence, connections, credentials)
2) Tarantool config storage (?)
3) Sharding
4) Tarantool EE
5) tt docs
6) Config module API
7) Developing applications

 
### General config settings

- [x] https://github.com/tarantool/doc/issues/4012 (1)
- [x] https://github.com/tarantool/doc/issues/4013 (1)
- [x] https://github.com/tarantool/doc/issues/3666 (1)
- [x] https://github.com/tarantool/doc/issues/3660 (1)

### Tarantool config storage 

- [x] https://github.com/tarantool/enterprise_doc/issues/265

### How-to 

- [x] https://github.com/tarantool/doc/issues/3659 (1)
- [x] https://github.com/tarantool/doc/issues/3921 (1)

### Tarantool EE 

- [x] https://github.com/tarantool/doc/issues/3665
- [x] https://github.com/tarantool/doc/issues/3667
- [x] https://github.com/tarantool/doc/issues/3668
- [x] https://github.com/tarantool/doc/issues/3669

### Administration 

- [x] https://github.com/tarantool/doc/issues/3666

### Reference 

- [x] https://github.com/tarantool/doc/issues/3924

### Misc 

- [x] [Configuration diagram] https://github.com/tarantool/doc/issues/3849

**Comment by andreyaksenov** [comment]
The idea of future structure for the `Configuration` section:

- Configuration
  - Configuration overview
    - Storing configuration in etcd
    - Storing configuration in Tarantool
    - ...
  - In-memory storage
  - Persistence
  - Replication
  - Sharding
  - Connections
  - Access control
  - Authentication
  - Logging
  - ...

Note that the exisitng [Configuration options overview](https://www.tarantool.io/en/doc/latest/concepts/configuration/#configuration-options-overview) section will be removed when corresponding topics for specific subsystems are ready (missing topics: `Access control`, `In-memory storage`, `Persistence`). The `Configuration` topic will be renamed to `Configuration overview`.
