### ISSUE TITLE
[Epic] TDB(iproto) documentation Q1, релиз 1.0

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#4002]
**Related dev. epic:** TDB
**PM ref.:** https://www.notion.so/tarantool/Tarantool-DB-fa2be9a557c941c18b5ec26819014d50
**SME:** @ a1div0  @ Galiev-Ruslan 

## Details

Текущие черновики (пишет @a1div0)
- https://github.com/tarantool/kvee/tree/master#readme
- https://github.com/tarantool/kvee/tree/master/doc

Структура, комментарии и скоуп работы:
- https://docs.google.com/document/d/1t0s0CWA6iEyzbvr7dbQlgFqfg1_yjja5JTOd7TF2EHw/edit

TDB is a multi-protocol DB.
Currently, two protocols are supported:
1. iproto
2. resp (redis)

Q1'24:

- [x] https://github.com/tarantool/doc/issues/4072
- [x] https://github.com/tarantool/doc/issues/4070
- [x] https://github.com/tarantool/doc/issues/4066
- [x] https://github.com/tarantool/doc/issues/4074
- [x] https://github.com/tarantool/doc/issues/4067
- [x] https://github.com/tarantool/doc/issues/4073
- [x] https://github.com/tarantool/doc/issues/4069
- [x] https://github.com/tarantool/doc/issues/4068

Q2'24:

- [x] https://github.com/tarantool/doc/issues/4141

Connected issue: https://github.com/tarantool/doc/issues/4028

**Comment by xuniq** [comment]
Q2 epic: https://github.com/tarantool/doc/issues/4210
