### ISSUE TITLE
[Epic] TCS documentation (initial)

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#4004]
**Product**: Tarantool Column Store 
**PM ref.:** https://www.notion.so/tarantool/Tarantool-Column-Store-3f73c27b39a6495da1aebbd5b7a5c60a?pvs=18
**SME:** @ Galiev-Ruslan , @ spozdeevvk 

## Details

Existing content from PM and dev (somewhere outdated):
- User's guide: https://www.notion.so/tarantool/Tarantool-Column-Store-098d0eb53c7f47229d07d8845909ac8c
- Admin/maintenance guide: https://www.notion.so/tarantool/d1a2c2bd1d064501ae9b6c212072f5f3#9c14855d5cae479f99fd0acaf7a90098
- Indexes: https://www.notion.so/tarantool/Tarantool-Column-Store-a939ac6c1c924b298f499e0e57cc8fbc

Doc repo: https://github.com/tarantool/tcs-doc

```[tasklist]
### User guide
- [ ] https://github.com/tarantool/doc/issues/4098
- [ ] https://github.com/tarantool/doc/issues/4099
- [ ] https://github.com/tarantool/doc/issues/4100
- [ ] https://github.com/tarantool/doc/issues/4101
- [ ] https://github.com/tarantool/doc/issues/4110
- [x] TCS: User guide > Instance config
```

```[tasklist]
### API reference
- [ ] https://github.com/tarantool/doc/issues/4102
- [ ] https://github.com/tarantool/doc/issues/4103
```

```[tasklist]
###  Installation guide
- [ ] https://github.com/tarantool/doc/issues/4104
```

```[tasklist]
### Administration guide
- [ ] https://github.com/tarantool/doc/issues/4146
```
