### ISSUE TITLE
[Epic] TCF documentation MVP Q2

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#4005]
**Next (Q3) epic:** https://github.com/tarantool/doc/issues/4287

**GH repo:** https://github.com/tarantool/cluster-federation
**PM ref.:** https://www.notion.so/tarantool/TCF-17ebdcdd3acd4752bab530b254972d79
**SME:** @ grafin
**Related CI issue:** https://github.com/tarantool/doc/issues/4160

## Details

Возможная структура документации TCF:

- [ ] Общая информация (MVP)
- [x] #4226
- [ ] https://github.com/tarantool/doc/issues/4233
  - [ ] #4176 (MVP, частично)
     - [ ] #4231 (Not implemented yet)
  - [ ] #4177 (MVP)
  - [x] #4227
  - [x] #4228
  - [x] #4229
  - [x] #4179
- [x] #4230
   - [x] #4180 (MVP, будет обновляться по мере необходимости)
- [ ] Справочники
  - [x] #4192 (MVP)
  - [x] #4181 (MVP)
  - [x] #4182 (MVP)
  - [x] #4183 (MVP)
  - [x] #4184 (MVP)
  - [x] #4178 (MVP)
  - [x] #4225

Разное:
- [x] #4232
- [x] #4234

**Comment by andreyaksenov** [comment]
Быстрый старт (черновик): https://docs.google.com/document/d/1QMmQNdW8iJzpO-5dGKbwGKb5LYt9xHJ-eNoghmI4KH4/edit?usp=sharing
