### ISSUE TITLE
[Epic] TDB (RESP) documentation Q2

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4127]
**Related dev. epic:** TBD
**PM ref.:** https://www.notion.so/tarantool/Tarantool-DB-fa2be9a557c941c18b5ec26819014d50
**SME:** @ AlgebraicWolf  @ Galiev-Ruslan @ LeonidVas 

Follow-up: https://github.com/tarantool/doc/issues/4257

## Current drafts

https://github.com/tarantool/tdb-redis/blob/master/README.md
https://github.com/tarantool/tdb-redis/tree/master/docs (commands. user)

TDB is a multi-protocol DB.
Currently, two protocols are supported:

- iproto
- resp (redis)

## Structure:

TDB (RESP)

- Общая информация
- Руководство по установке
   - Установка через ATE
   - Установка с помощью Docker-образа
- Руководство администратора
   - Развертывание
      - через TT CLI
      - через ATE
      - с помощью Docker-образа
   - TLS
   - ACL
- Руководство пользователя
  - Миграции
- Команды Redis
- Журнал изменений

# Scope

- [x] https://github.com/tarantool/doc/issues/4172
- [x] https://github.com/tarantool/doc/issues/4131
- [x] https://github.com/tarantool/doc/issues/4130
- [x] https://github.com/tarantool/doc/issues/4173
- [x] https://github.com/tarantool/doc/issues/4143
- [x] https://github.com/tarantool/doc/issues/4132
- [x] https://github.com/tarantool/doc/issues/4168
- [x] https://github.com/tarantool/doc/issues/4138
