### ISSUE TITLE
[Epic] 3.1 - Improvements in error handing

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4137]
**Product:** Tarantool
**Since:** 3.1
**Root document:** https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_error/
**SME:** @ Gumix, @ CuriousGeorgiy

# Issues

- [ ] https://github.com/tarantool/doc/issues/4047
- [ ] https://github.com/tarantool/doc/issues/4049
- [ ] https://github.com/tarantool/doc/issues/4052
- [ ] https://github.com/tarantool/doc/issues/4057
- [ ] https://github.com/tarantool/doc/issues/4076
- [ ] https://github.com/tarantool/doc/issues/4087
- [ ] https://github.com/tarantool/doc/issues/4107
- [ ] https://github.com/tarantool/doc/issues/4126
