### ISSUE TITLE
[Epic] Update the 'Administration' section

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4154]
**Related doc issue:** https://github.com/tarantool/doc/issues/3177

**Product:** Tarantool
**Since:** 3.0
**Audience/target:** admins
**Root document:** https://www.tarantool.io/en/doc/latest/book/admin/
**SME:** 

# Details

There are a set of changes in the 3.0 version of Tarantool that might affect docs in the Administration section:
- Tarantool uses a new approach for developing cluster applications (epic https://github.com/tarantool/doc/issues/3920). This is not documented yet.
- To package the resulting application before deployment, the `tt pack` command can be used.
- The recommended way of deploying and administering cluster application for Enterprise customers is [Ansible Tarantool Enterprise](https://www.tarantool.io/en/devops/latest/).
- TCM also allows performing many administrative tasks (switching leaders, monitoring, etc.)

Taking into account all of these, it is necessary to revise the Administration section. Ideas for possible structure: https://docs.google.com/document/d/1F_looF24B6Ai0BL2JNWgVdbLcDcTPJhzVcVOuogDymA/edit?usp=sharing

Note that there are different kind of "layers" of administering a cluster:

- Tarantool database specifics: connection types, access control, memory usage, configuration errors, etc.
- Tooling used for administration: system tools (for example, `systemd`), tt CLI, ATE, TCM.

## Related issues

- [ ] https://github.com/tarantool/doc/issues/3812
- [ ] https://github.com/tarantool/doc/issues/3814
- [ ] https://github.com/tarantool/doc/issues/3815
- [ ] https://github.com/tarantool/doc/issues/3916
