### ISSUE TITLE
[Epic] TDB(iproto) documentation 2.0 Q2

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4210]
This epic includes tickets for the upcoming 2.0 release.

**PM ref.:** https://www.notion.so/tarantool/Tarantool-DB-fa2be9a557c941c18b5ec26819014d50
**SME:** @ a1div0   @ mooncfrat2019  @ Galiev-Ruslan @ Satbek 

Connected doc epics in the tarantool/tarantooldb repo:

1) https://github.com/tarantool/tarantooldb/issues/423
2) https://github.com/tarantool/tarantooldb/issues/422

Total estimation: ≈12

### Общие разделы

- [x] https://github.com/tarantool/doc/issues/4242

### Разделы с запускаемыми примерами

- [x] https://github.com/tarantool/tarantooldb/issues/328 (поправить запуск и настройку стенда)
- [x] https://github.com/tarantool/tarantooldb/issues/340 (поправить запуск и настройку стенда)
- [x] https://github.com/tarantool/tarantooldb/issues/332 - пример удаляется
- [x] https://github.com/tarantool/tarantooldb/issues/333 (поправить запуск и настройку стенда, актуализировать описание примера миграций, возможно, он будет новый)
- [x] https://github.com/tarantool/tarantooldb/issues/336 (поправить запуск и настройку стенда, актуализировать описание примеров в тч определение конфигурации)
- [x] https://github.com/tarantool/tarantooldb/issues/334
- [x] https://github.com/tarantool/tarantooldb/issues/338

**Comment by xuniq** [comment]
TDB Q3 epic: https://github.com/tarantool/doc/issues/4277
