### ISSUE TITLE
[Epic] tt CLI 2.3.0 docs Q3

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#4223]
**Product:** tt cli
**Since:** tt 2.3.0
**Audience/target:** all
**Root document:** https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/
**SME:** @ psergee 

# Details

Documentation for tt 2.3.0 updates and minor features of earlier versions that were skipped before.

# Tasks

10 sp:

- [x] Integrity check in tt-ee:
  - [x] https://github.com/tarantool/enterprise_doc/issues/261
  - [x] https://github.com/tarantool/enterprise_doc/issues/262
  - [x] https://github.com/tarantool/enterprise_doc/issues/263 
- [x] #4142
- [x] #4201 
- [x] #4241 
- [x] #4261

**Comment by andreyaksenov** [comment]
Looks like we missed the `tt binaries list` and `tt binaries switch` subcommands: https://github.com/tarantool/tt/pull/725/commits/5ee9f3455b138bc8c67f190786c77d42d794331d

**Comment by p7nov** [comment]
> Looks like we missed the `tt binaries list` and `tt binaries switch` subcommands: [tarantool/tt@5ee9f34](https://github.com/tarantool/tt/commit/5ee9f3455b138bc8c67f190786c77d42d794331d)

#4026 is on the list
