### ISSUE TITLE
TCF: Руководство по установке

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4226]
Пример TCS: https://docs.d.tarantool.io/ru/column-store/doc/installation-guide/installation_guide/
Пример TDB: https://www.tarantool.io/ru/tarantooldb/doc/latest/install_and_upgrade/

1) основной кейс установки - через ATE, делаем ссылки на доку ATE с необходимыми уточнениями: https://www.tarantool.io/en/devops/latest/docker-scenarios-products/#tarantool-clusters-federation

в банке нетипичная установка (2 gateways - 2 destinations), отдельно про это не пишем, но указываем примечанием, какие рекомендации есть при установке (рекомендованное количество серверов на кол-во gateway-destination);

2) ручная установка

# To-Do

- [x] Добавить информацию про установку и деплой TCF через ATE
- [x] Описать ручную установку
- [x] Привести пример настройки ролей tcf для кластеров в инвентаре ATE  (сделано в рамках https://gitlab.corp.mail.ru/tarantool/delivery/ansible-tarantool-enterprise/-/merge_requests/149)
- [x] Дополнить соответствующие разделы по TCF в документации ATE (сделано в рамках https://gitlab.corp.mail.ru/tarantool/delivery/ansible-tarantool-enterprise/-/merge_requests/149

**Comment by xuniq** [comment]
Related MR: https://gitlab.corp.mail.ru/tarantool/delivery/ansible-tarantool-enterprise/-/merge_requests/149
