### ISSUE TITLE
[Epic] TCS Q3

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#4260]
**PM ref.:**
* TCS releases: https://jira.vk.team/browse/PRODUCTS-682  
* Client-oriented plans (spreadsheet): https://docs.google.com/spreadsheets/d/1rV80PELwTgO5UpvgAFmxF60808HtmNkOwss3YPgeNDk/edit?gid=337754851#gid=337754851
**SME:** @ Galiev-Ruslan 

# Details

Release 0.22:
- [x] https://github.com/tarantool/doc/issues/4493

Release 0.21:
- [x] https://github.com/tarantool/doc/issues/4214
- [x] https://github.com/tarantool/doc/issues/4444
- [x] https://github.com/tarantool/doc/issues/4445
- [x] https://github.com/tarantool/doc/issues/4217

Release 0.20.5:
- [x] https://github.com/tarantool/doc/issues/4432
- [x] https://github.com/tarantool/doc/issues/4434
- [x] https://github.com/tarantool/doc/issues/4441

Release 0.19-0.20.3:
- [x] https://github.com/tarantool/doc/issues/4414
- [x] https://github.com/tarantool/doc/issues/4415
- [x] https://github.com/tarantool/doc/issues/4416
- [x] https://github.com/tarantool/doc/issues/4417
- [x] https://github.com/tarantool/doc/issues/4418

Release 0.18:
- [x] https://github.com/tarantool/doc/issues/4337
- [x] https://github.com/tarantool/doc/issues/4340
- [x] https://github.com/tarantool/doc/issues/4339
- [x] https://github.com/tarantool/doc/issues/4342
- [x] https://github.com/tarantool/doc/issues/4343

Surgut EOJuly:
- [x] https://github.com/tarantool/doc/issues/4211

Tech debts:
- [x] https://github.com/tarantool/doc/issues/4408
