### ISSUE TITLE
[Epic] TDB(iproto) documentation 2.0 Q3

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4277]
This epic includes tickets for the upcoming 2.0 release.

**PM ref.:** https://www.notion.so/tarantool/Tarantool-DB-fa2be9a557c941c18b5ec26819014d50
**SME:** @ a1div0  @ Galiev-Ruslan @ Satbek @ mooncfrat2019 

Total estimation: ≈33

Connected doc epics in the tarantool/tarantooldb repo:

1) https://github.com/tarantool/tarantooldb/issues/423
2) https://github.com/tarantool/tarantooldb/issues/422

### Общие разделы

- [x] https://github.com/tarantool/doc/issues/4274
- [x] https://github.com/tarantool/doc/issues/4310
- [x] https://github.com/tarantool/tarantooldb/issues/327
- [x] https://github.com/tarantool/tarantooldb/issues/324
- [x] https://github.com/tarantool/tarantooldb/issues/629
- [x] https://github.com/tarantool/tarantooldb/issues/630
- [x] https://github.com/tarantool/doc/issues/4239
- [x] https://github.com/tarantool/doc/issues/4377 
- [x] https://github.com/tarantool/tarantooldb/issues/325
- [x] https://github.com/tarantool/tarantooldb/issues/322
- [x] https://github.com/tarantool/doc/issues/4378 - задача на актуализацию разделов по ATE
- [x] https://github.com/tarantool/tarantooldb/issues/326
- [x] https://github.com/tarantool/tarantooldb/issues/323
- [x] https://github.com/tarantool/tarantooldb/issues/321
- [x] https://github.com/tarantool/tarantooldb/issues/344 

### Разделы с запускаемыми примерами

- [x] https://github.com/tarantool/tarantooldb/issues/335 (Поправить запуск и настройку стенда)
- [x] https://github.com/tarantool/tarantooldb/issues/331 (Поправить запуск и настройку стенда)
- [x] https://github.com/tarantool/tarantooldb/issues/515 (Поправить запуск и настройку стенда)
- [x] https://github.com/tarantool/tarantooldb/issues/339 (Поправить запуск и настройку стенда + актуализировать описание примеров (в тч определение конфигурации)
- [x] https://github.com/tarantool/doc/issues/4388
- [x] https://github.com/tarantool/doc/issues/4375 (Поправить запуск и настройку стенда + актуализировать описание примеров (в тч определение конфигурации))
- [x] https://github.com/tarantool/tarantooldb/issues/329 (вычитать новую инструкцию, обновить ее после доработки примера)
- [x] https://github.com/tarantool/tarantooldb/issues/330 (поправить запуск и настройку стенда)
- [x] https://github.com/tarantool/tarantooldb/issues/337 (Поправить запуск и настройку стенда + актуализировать описание примеров (в тч определение конфигурации)
- [x] https://github.com/tarantool/tarantooldb/issues/341 (поправить запуск и настройку стенда, актуализировать описание примера миграций, возможно, он будет новый)
- [x] https://github.com/tarantool/tarantooldb/issues/601 (уточнения по примерам slow_log, go_crud, go_balancer)
