### ISSUE TITLE
[Epic] TDB(iproto) documentation 1.x Q3

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4278]
This epic includes tickets for :
- the upcoming 1.x releases;
- tech debt tickets.

**PM ref.:** https://www.notion.so/tarantool/Tarantool-DB-fa2be9a557c941c18b5ec26819014d50
**SME:** @ a1div0  @ Galiev-Ruslan @ Satbek 

## Details

Tech debt:

- [x] https://github.com/tarantool/doc/issues/4220

1.2:

- [x] https://github.com/tarantool/doc/issues/4354
- [x] https://github.com/tarantool/doc/issues/4359
- [x] https://github.com/tarantool/doc/issues/4366
- [x] https://github.com/tarantool/doc/issues/4389

**Comment by xuniq** [comment]
Q4 epic: https://github.com/tarantool/doc/issues/4355
