### ISSUE TITLE
[Epic] TCF 0.3.0 (Q4)

### ISSUE THREAD

**Issue by andreyaksenov** [tarantool/doc#4287]
**Previous (Q2) epic:** https://github.com/tarantool/doc/issues/4005

**GH repo:** https://github.com/tarantool/cluster-federation
**PM ref.:** https://www.notion.so/tarantool/TCF-17ebdcdd3acd4752bab530b254972d79
**SME:** @ grafin  @ DifferentialOrange @ oleg-jukovec @ themilchenko 
**Related CI issue:** https://github.com/tarantool/doc/issues/4600
**Release 0.3.1:** https://jira.vk.team/browse/PRODUCTS-1330

Приняли решение разделить доку TCF на 2 ветки:
- 0.2.0 - поддержка только Tarantool 2.x
- 0.3.0 и выше (latest) - одновременная поддержка Cartridge + Tarantool 3.x, положить рядом в одну доку инструкции для 2.х и 3.х

## Details

Что было сделано (13 sp):

- [x] #4525
- [x] #4311 
- [x] #4517 
- [x] #4697

---------------

Возможная структура документации TCF:

- [ ] Общая информация (MVP)
- [x] #4226
- [x] https://github.com/tarantool/doc/issues/4233
  - [x] #4176 (MVP, частично)
     - [x] (0.3.0) #4525
     - [ ] #4231 (Not implemented yet)
  - [x] #4177 (MVP)
     - [x] (0.3.0) #4311 
  - [ ] (0.3.0) #4524
  - [x] #4227
  - [x] #4228
  - [x] #4229
  - [x] #4179
- [x] #4230
   - [x] #4180 (MVP, будет обновляться по мере необходимости)
- [ ] Справочники
  - [x] (0.3.0) https://github.com/tarantool/doc/issues/4697
  - [x] (0.3.0) #4713
  - [x] (0.3.0) #4312 
  - [ ] (0.3.0) #4225
  - [ ] (0.3.0) #4396
  - [x] #4192 (MVP)
  - [x] #4181 (MVP)
  - [x] #4182 (MVP)
  - [x] #4183 (MVP)
  - [x] #4184 (MVP)
  - [x] #4178 (MVP)

Разное:
- [x] #4232
- [x] #4234
- [x] #4517
- [x] https://github.com/tarantool/doc/issues/4526
- [x] https://github.com/tarantool/doc/issues/4628 - делать это вместо отдельных whats new для релизов в 2024

TCF 0.4.0 epic: https://github.com/tarantool/doc/issues/4523
TCF 0.5.0 epic: https://github.com/tarantool/doc/issues/4532
TCF 0.6.0: https://github.com/tarantool/doc/issues/4556

**Comment by xuniq** [comment]
Related issue: https://github.com/tarantool/doc/issues/4600

**Comment by xuniq** [comment]
Done
