### ISSUE TITLE
[Epic] Java EE connector documentation

### ISSUE THREAD

**Issue by veod32** [tarantool/doc#4345]
**Related dev. epic:** GitHub link
**PM ref.:** Notion link
**SME:** @ dkasimovskiy 

## Details

**Total sp: 34**

- [ ] Quick start (возможно по образцу https://www.tarantool.io/en/doc/latest/how-to/getting_started_go) 5
- [ ] Installation 3
- [ ] Architecture, description of conponents 5
- [ ] Connection pooling/balancing 3
- [ ] Spring Data 5
- [ ] API (~ 20 методов CRUD, ~ 20 методов box а-ля box.net) -- есть JavaDoc, возможно импортировать в md? 3
- [ ] https://www.tarantool.io/en/doc/latest/book/connectors/java/ -- page refactoring 2
- [ ] Metrics & Dashboard 5
- [ ] Describe the CRUD and box clients 5
