### ISSUE TITLE
[Epic] tt CLI 2.4 docs Q3

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#4387]
**Related dev. issue(s):** GitHub link(s)

**Product:** tt Cli
**Since:** 2.4
**Audience/target:** all
**Root document:** https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/
**SME:** @ oleg-jukovec 

# Details

An epic for tt CLI 2.4 documentation tasks.

# Tasks

- [x] tt-ee migrations:
  - [x] https://github.com/tarantool/enterprise_doc/issues/269
  - [x] https://github.com/tarantool/enterprise_doc/issues/277
  - [x] https://github.com/tarantool/enterprise_doc/issues/278
  - [x] https://github.com/tarantool/enterprise_doc/issues/279
- [x] #4362 
- [x] #4376
- [x] #4308
- [x] #4313
- [x] #4447 
- [x] #4392
- [x] #4449 

Total: 16 sp
