### ISSUE TITLE
[Epic] tt CLI 2.5 docs 

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#4473]
**Related dev. issue(s):** GitHub link(s)

**Product:** tt Cli
**Since:** 2.5
**Audience/target:** all
**Root document:** https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/
**SME:** @ oleg-jukovec 

# Details

An epic for tt CLI 2.5 documentation tasks.
[Changelog](https://github.com/tarantool/tt/releases/tag/v2.5.0)

# Tasks

- [x] #4433 
- [x] #4467 
- [x] #4471 
- [x] #4480
- [x] #4566 
- [x] #4606 
- [x] #4607
- [x] https://github.com/tarantool/enterprise_doc/issues/283
- [x] https://github.com/tarantool/enterprise_doc/issues/284
- [x] https://github.com/tarantool/enterprise_doc/issues/285
