### ISSUE TITLE
[Epic] TCS Q4

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#4522]
**PM ref.:**
* TCS releases: https://jira.vk.team/browse/PRODUCTS-682  
* Client-oriented plans (spreadsheet): https://docs.google.com/spreadsheets/d/1WNJPARAn1xUZxjGQD_HOzdQJendiePyoGdBDzTaf2vw/edit?gid=0#gid=0
**SME:** @ Galiev-Ruslan 

# Details

Release 0.25:
- [x] https://github.com/tarantool/doc/issues/4528
- [x] https://github.com/tarantool/doc/issues/4675
- [x] https://github.com/tarantool/doc/issues/4696
- [x] https://github.com/tarantool/doc/issues/4700

Release 0.24:
- [x] https://github.com/tarantool/doc/issues/4673
- [x] https://github.com/tarantool/doc/issues/4491
- [x] https://github.com/tarantool/doc/issues/4492
- [x] https://github.com/tarantool/doc/issues/4627
- [x] https://github.com/tarantool/doc/issues/4630
- [x] https://github.com/tarantool/doc/issues/4631
- [x] https://github.com/tarantool/doc/issues/4654
- [x] https://github.com/tarantool/doc/issues/4655

Release 0.23.1:
- [x] https://github.com/tarantool/doc/issues/4605
- [x] https://github.com/tarantool/doc/issues/4602

Tech debt:
- [x] https://github.com/tarantool/doc/issues/4585
- [x] https://github.com/tarantool/doc/issues/4586
