### ISSUE TITLE
[Epic] TDB (IPROTO) 2.x: future plans

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4544]
This epic includes tickets for the upcoming 2.x releases.

**SME:** @ a1div0  @ Galiev-Ruslan @ Satbek @ mooncfrat2019 
Client-oriented plans (spreadsheet): https://docs.google.com/spreadsheets/d/1WNJPARAn1xUZxjGQD_HOzdQJendiePyoGdBDzTaf2vw/edit?gid=0#gid=0

Total estimation: ≈

# Details

Future releases:

- [ ] https://github.com/tarantool/doc/issues/4567
- [ ] https://github.com/tarantool/doc/issues/4390
- [ ] https://github.com/tarantool/doc/issues/4547
- [ ] https://github.com/tarantool/doc/issues/4546
- [ ] https://github.com/tarantool/doc/issues/4545
- [x] https://github.com/tarantool/doc/issues/4582
- [ ]  https://github.com/tarantool/doc/issues/4554
