### ISSUE TITLE
[Epic] TDB (iproto): ГосТех

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4564]
**PM ref.:** 
**SME:** @ a1div0 @ veod32  @ Galiev-Ruslan @ Satbek @ mooncfrat2019 
Client-oriented plans (spreadsheet): https://docs.google.com/spreadsheets/d/1WNJPARAn1xUZxjGQD_HOzdQJendiePyoGdBDzTaf2vw/edit?gid=0#gid=0
**Dev issues:** 

Total estimation: ≈ ?

Необходимо подготовить документацию согласно требованиям ГосТех.

## Details

- [ ] https://github.com/tarantool/doc/issues/4555
- [ ] https://github.com/tarantool/doc/issues/4548
- [ ] https://github.com/tarantool/doc/issues/4571
- [ ] https://github.com/tarantool/doc/issues/4572
- [ ] https://github.com/tarantool/doc/issues/4573
- [ ] https://github.com/tarantool/doc/issues/4567
- [ ] https://github.com/tarantool/doc/issues/4574
