### ISSUE TITLE
[Epic] TDB (RESP): future plans

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4583]
**PM ref.:** https://www.notion.so/tarantool/Tarantool-DB-fa2be9a557c941c18b5ec26819014d50
**Source:** https://github.com/tarantool/tdb-redis/tree/master/docs/public
**SME:** @ AlgebraicWolf  @ Galiev-Ruslan @ LeonidVas @ 0x501D 

Follow-up of https://github.com/tarantool/doc/issues/4257

# Details

Release 1.5.0 :

- [ ] инструкция SELECT (https://jira.vk.team/browse/TNTP-73)

??? Not planned yet ???:

- [ ] https://github.com/tarantool/doc/issues/4134 (not implemented yet)
- [ ] https://github.com/tarantool/doc/issues/4133 (blocked - not implemented yet)
- [ ] https://github.com/tarantool/doc/issues/4643
