### ISSUE TITLE
[Epic] tt CLI 2.7

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#4689]
**Product:** tt CLI
**Since:** 2.7
**Audience/target:** all
**Root document:** https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/
**SME:** @ oleg-jukovec 

# Details

An epic for tt CLI 2.7 documentation tasks.
[Jira](https://jira.vk.team/projects/TNTP/versions/167467)

# Issues

- [ ] https://github.com/tarantool/doc/issues/4726
- [ ] https://github.com/tarantool/doc/issues/4691
- [ ] https://github.com/tarantool/doc/issues/4702
- [ ] https://github.com/tarantool/doc/issues/4701
- [ ] https://github.com/tarantool/doc/issues/4735
- [ ] https://github.com/tarantool/doc/issues/4731
- [ ] https://github.com/tarantool/doc/issues/4715
- [ ] https://github.com/tarantool/doc/issues/4722
- [ ] https://github.com/tarantool/doc/issues/4679
- [ ] https://github.com/tarantool/doc/issues/4687
- [ ] https://github.com/tarantool/doc/issues/4732
