### ISSUE TITLE
[Epic] tt CLI 2.8

### ISSUE THREAD

**Issue by p7nov** [tarantool/doc#4690]
**Product:** tt CLI
**Since:** 2.8
**Audience/target:** all
**Root document:** https://www.tarantool.io/en/doc/latest/reference/tooling/tt_cli/
**SME:** @ oleg-jukovec 

# Details

An epic for tt CLI 2.8 documentation tasks.
[Jira](https://jira.vk.team/projects/TNTP/versions/167495)

# Issues

- [ ] https://github.com/tarantool/doc/issues/4973
- [ ] https://github.com/tarantool/doc/issues/4962
- [ ] https://github.com/tarantool/doc/issues/4956
- [ ] https://github.com/tarantool/doc/issues/4957
- [ ] https://github.com/tarantool/doc/issues/5441
