### ISSUE TITLE
[Epic] CDC Q1 2025

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#4698]
**PM ref.:**
* CDC in Jira: https://jira.vk.team/browse/PRODUCTS-679
* CDC in Confluence: https://confluence.vk.team/display/TSE/Tarantool+CDCv9?src=contextnavpagetreemode
* CDC in GitLab: https://gitlab.corp.mail.ru/tarantool/cdc/v9/tarantool-cdc
* CDC dev docs:
  * Dev docs in md:  https://gitlab.corp.mail.ru/tarantool/cdc/v9/tarantool-cdc/-/tree/master/doc
  * Anna Balaeva's readme: https://gitlab.corp.mail.ru/tarantool/k8s/helm-chart-cdc

**SME:** @ dkasimovskiy 

**Doc draft deployed here:** https://docs.d.tarantool.io/ru/cdc/doc/doc-draft/

# Details

We need to finalize the initial draft of our doc set.

Doc set parts:
- [x] https://github.com/tarantool/doc/issues/4588
- [x] https://github.com/tarantool/doc/issues/4760
- [x] https://github.com/tarantool/doc/issues/4587 -- section "Values" for Q1, section "Metrics" for Q2
