### ISSUE TITLE
[Epic] TDB (iproto) 2.x: release 2.2.0 (Q1'25)

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4706]
This epic includes tickets for the upcoming 2.2.0 release.

**Dev epic for 2.2.0 release:** https://jira.vk.team/browse/PRODUCTS-1368
**PM ref.:** 
**SME:** @ a1div0  @ Galiev-Ruslan @ Satbek @ mooncfrat2019 
**Release date:** 17.02.2025

Total estimation:

## Details

- [x] https://github.com/tarantool/doc/issues/4707
- [x] https://github.com/tarantool/doc/issues/4708
- [x] Поддержка ОС Astra Linux 1.8
- [x] https://github.com/tarantool/doc/issues/4738

**Comment by xuniq** [comment]
Done
