### ISSUE TITLE
[Epic] TDB (iproto): Tech debt & Operation Q1'25

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4709]
This epic includes tech debt and operation tickets for the 1.x and 2.x releases.

**SME:** @ a1div0  @ Galiev-Ruslan @ Satbek @ mooncfrat2019

## Details

Tech debt & Operation:

- [x] https://github.com/tarantool/doc/issues/4597
- [x] https://github.com/tarantool/doc/issues/4598
- [x] https://github.com/tarantool/doc/issues/4642
- [x] https://github.com/tarantool/doc/issues/4681
- [x] https://github.com/tarantool/doc/issues/4765
- [x] https://github.com/tarantool/doc/issues/4764

**Comment by xuniq** [comment]
Epic for Q2'25: https://github.com/tarantool/doc/issues/5013

**Comment by xuniq** [comment]
Done.
