### ISSUE TITLE
[Epic] TCF 0.7.0

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4711]
**GH repo:** https://github.com/tarantool/cluster-federation
**SME:** @ DifferentialOrange @ oleg-jukovec @ themilchenko 
**Release date:** 25.02.25
**Branch:** latest (0.3.0+)
TCF release:
- https://jira.vk.team/browse/PRODUCTS-1628

Rough estimation: 8 sp (20.12.24)

## 0.7.0 scope

- [x] https://github.com/tarantool/doc/issues/4741
- [x] https://github.com/tarantool/doc/issues/4746
- [x] https://github.com/tarantool/doc/issues/4747
- [x] whats new (будет написан в рамках https://github.com/tarantool/doc/issues/4628)

The following ticket from the 0.7.0 scope is moved to [Q2'25 Install Guide Tech debt epic](https://github.com/tarantool/doc/issues/5043): https://github.com/tarantool/doc/issues/4960 

## Что берем в работу к релизу 0.7.0:

- Общая информация (возможно, стоит расширить инфой из доков по фстэку)
- [x] #4226
- Руководство пользователя
  - [x] #4231 - раздел Архитектура
  - [x] #4227
  - [x] #4228
  - [x] #4741
  - [x] #4747
  - [x] #4524 **2 приоритет**
  - [ ] https://github.com/tarantool/doc/issues/4541 **2 приоритет**
  - [ ] https://github.com/tarantool/doc/issues/4756 **2 приоритет**
- Руководство администратора
   - [x] #4229
   - [x] #4179
   - [x] https://github.com/tarantool/doc/issues/4746
   - [x] https://github.com/tarantool/doc/issues/4762
   - [x] https://github.com/tarantool/doc/issues/4761
   - [x] https://github.com/tarantool/doc/issues/4953
- Справочники
  - [x] https://github.com/tarantool/doc/issues/4624
  - [x] https://github.com/tarantool/doc/issues/4750
  - [x] https://github.com/tarantool/doc/issues/4745
  - [x] https://github.com/tarantool/doc/issues/4688
  - [x] https://github.com/tarantool/doc/issues/4232
  - [ ] https://github.com/tarantool/doc/issues/4542 **2 приоритет**
  - [x] #4225 **2 приоритет**
  - [x] #4396 **2 приоритет**
- Примечания к версиям
   - [ ] https://github.com/tarantool/doc/issues/4628 - делать это вместо отдельных whats new для релизов 0.3.0-0.7.0

## Полная структура задач по TCF:

> Некоторые разделы в списке ниже помечены специальными комментариями:
> - **WIP** - страница в разработке, в текущий скоуп для ПСБ эта задача не попадет;
> - **2 приоритет** - задача попала в скоуп во второй приоритет, скорее всего она будет сделана после 25.02.25.

> Если для задачи с такой пометкой нужна новая отдельная страница/раздел, нужно завести "рыбу" - шаблон соответствующей страницы/раздела. Нужно для задачи https://github.com/tarantool/doc/issues/4763

- [ ] Общая информация
- [x] #4226
  - [x] https://github.com/tarantool/doc/issues/4960 
- [x] https://github.com/tarantool/doc/issues/4233
  - [x] #4176 
     - [x] #4525
     - [x] #4231 
     - [ ] https://github.com/tarantool/doc/issues/4625 (в скоуп пока не берем) **WIP** (выяснить, нужна ли для  фичи отдельная страница, чтобы ее подсветить)
  - [x] #4177 
     - [x] (0.3.0) #4311 
     - [ ] https://github.com/tarantool/doc/issues/4965
  - [x] (0.3.0) #4312 
  - [ ] (0.3.0) #4524 **2 приоритет**
  - [x] #4227
  - [x] #4228
  - [x] https://github.com/tarantool/doc/issues/4741
  - [x] https://github.com/tarantool/doc/issues/4747
  - [ ] https://github.com/tarantool/doc/issues/4539 (в скоуп пока не берем) **WIP**
  - [ ] https://github.com/tarantool/doc/issues/4541 **2 приоритет**
  - [ ] https://github.com/tarantool/doc/issues/4756 **2 приоритет**
- [x] #4230
   - [x] #4229
   - [x] #4179
   - [x] https://github.com/tarantool/doc/issues/4746
   - [x] https://github.com/tarantool/doc/issues/4761
   - [x] https://github.com/tarantool/doc/issues/4961
   - [x] https://github.com/tarantool/doc/issues/4953
   - [x] #4180 
      - [x] https://github.com/tarantool/doc/issues/4762
- [ ] Справочники
  - [x] (0.3.0) https://github.com/tarantool/doc/issues/4697
  - [x] (0.3.0) #4713
     - [x] https://github.com/tarantool/doc/issues/4624
     - [x] https://github.com/tarantool/doc/issues/4750
  - [ ] (0.3.0) #4225 **2 приоритет** (нужно выяснить, какую инфу будем заносить)
  - [ ] (0.3.0) #4396 **2 приоритет** (нужно выяснить, какую инфу будем заносить)
  - [x] https://github.com/tarantool/doc/issues/4972
  - [x] https://github.com/tarantool/doc/issues/4974
  - [x] #4192 (MVP)
  - [x] #4181 (MVP)
  - [x] #4182 
     - [x] https://github.com/tarantool/doc/issues/4745
     - [ ] https://github.com/tarantool/doc/issues/4542 **2 приоритет**
  - [x] #4183 (MVP)
     - [x] https://github.com/tarantool/doc/issues/4688
     - [x] https://github.com/tarantool/doc/issues/4232
  - [x] #4184 (MVP)
  - [x] #4178 (MVP)
- [ ] Примечания к версиям
   - [x] https://github.com/tarantool/doc/issues/4628 - делать это вместо отдельных whats new для релизов 0.3.0-0.7.0
   - [ ] https://github.com/tarantool/doc/issues/4752 (пока не берем в скоуп)

**Comment by maryiaLichko** [comment]
https://github.com/tarantool/doc/issues/4960 transferred to https://github.com/tarantool/doc/issues/5043
