### ISSUE TITLE
[Epic] TCF: Руководство пользователя (Q1'25 Tech Debt)

### ISSUE THREAD

**Issue by xuniq** [tarantool/doc#4712]
**GH repo:** https://github.com/tarantool/cluster-federation
**Root document:** https://www.tarantool.io/en/clustersfederation/doc/latest/user_guide/
**SME:** @ grafin  @ DifferentialOrange @ oleg-jukovec @ themilchenko
**Examples:**
- TDG: https://www.tarantool.io/en/tdg/latest/development/
- TCS: https://www.tarantool.io/ru/column-store/doc/latest/user_guide/
- MQ: https://www.tarantool.io/ru/queue-enterprise/doc/latest/user_guide/
- TDB: https://www.tarantool.io/en/tarantooldb/doc/latest/user_guide/

# General info about TCF docs

**Previous (Q2) epic:** https://github.com/tarantool/doc/issues/4287
**Related CI issue:** https://github.com/tarantool/doc/issues/4600
**Release 0.3.1:** https://jira.vk.team/browse/PRODUCTS-1330

Приняли решение разделить доку TCF на 2 ветки:
- 0.2.0 - поддержка только Tarantool 2.x
- 0.3.0 и выше (latest) - одновременная поддержка Cartridge + Tarantool 3.x, положить рядом в одну доку инструкции для 2.х и 3.х

Estimation: 44 sp (20.12.2024)
Estimation: 42 sp (30.01.2025) (the estimation includes all tech debt tickets - user guide, admin guide, reference, install guide)
Estimation: 20 sp (03.25) - user guide only
Estimation:  8 sp (25.03.25) - done in Q1'25

TCF 0.4.0 epic: https://github.com/tarantool/doc/issues/4523
TCF 0.5.0 epic: https://github.com/tarantool/doc/issues/4532
TCF 0.6.0: https://github.com/tarantool/doc/issues/4556
TCF 0.7.0: https://github.com/tarantool/doc/issues/4711

## Scope

- [x] https://github.com/tarantool/doc/issues/4231
- [x] https://github.com/tarantool/doc/issues/4312
- [x] https://github.com/tarantool/doc/issues/4228
- [x] https://github.com/tarantool/doc/issues/4628
- [x] https://github.com/tarantool/doc/issues/4763

## User guide structure

- Руководство пользователя
  - Архитектура
  - Управление TCF в веб-интерфейсе TCM
  - Настройка хранилища конфигурации и состояния TCF
  - Настройка межкластерных репликаторов
  - (0.7.0) Работа TCF с кластерами, запущенными в режиме синхронной репликации
  - (0.7.0) Расширения WAL
  - (0.5.0) Миграция кластеров Tarantool Cartridge на Tarantool 3.x с помощью TCF
  - (0.5.0) Использование TCF для объединения кластеров Tarantool Cartridge и Tarantool 3.x
  - (0.6.0) Использование TCF c кластерами Tarantool Column Store

## Полная структура документации TCF

- [ ] Общая информация (MVP)
- [x] #4226
- [x] https://github.com/tarantool/doc/issues/4233
  - [x] #4176 (MVP, частично)
     - [x] (0.3.0) #4525
     - [x] #4231 
  - [x] #4177 (MVP)
     - [x] (0.3.0) #4311 
  - [x] (0.3.0) #4312 
  - [x] (0.3.0) #4524
  - [x] #4227
  - [x] #4228
  - [x] #4229
  - [x] #4179
- [x] #4230
   - [x] #4180 (MVP, будет обновляться по мере необходимости)
   - [x] https://github.com/tarantool/doc/issues/4761
   - [x] https://github.com/tarantool/doc/issues/4961
   - [x] https://github.com/tarantool/doc/issues/4762
- [ ] Справочники
  - [x] (0.3.0) https://github.com/tarantool/doc/issues/4697
  - [x] (0.3.0) #4713
  - [ ] (0.3.0) #4225
  - [ ] (0.3.0) #4396
  - [x] https://github.com/tarantool/doc/issues/4972
  - [x] #4192 (MVP)
  - [x] #4181 (MVP)
  - [x] #4182 (MVP)
  - [x] #4183 (MVP)
     - [x] https://github.com/tarantool/doc/issues/4688
  - [x] #4184 (MVP)
  - [x] #4178 (MVP)
- [x] https://github.com/tarantool/doc/issues/4628 - делать это вместо отдельных whats new для релизов 0.3.0-0.7.0

Разное:
- [x] #4232
- [x] https://github.com/tarantool/doc/issues/4526
- [x] https://github.com/tarantool/doc/issues/4744 - настройка ci
- [ ] https://github.com/tarantool/doc/issues/4766 - использование терминов

**Comment by xuniq** [comment]
Q2'25 epic: https://github.com/tarantool/doc/issues/5015

**Comment by xuniq** [comment]
Done.
